//! GMS 1.4.9999 built-in names, mechanically extracted from the
//! Function_Add, AddConstant, and Variable_BuiltIn_Add calls in Runner14.c.
//! Keep these newline-delimited to minimize static table size.

pub const FUNCTIONS: &str = "\
abs
achievement_available
achievement_event
achievement_get_challenges
achievement_get_info
achievement_get_pic
achievement_increment
achievement_load_friends
achievement_load_leaderboard
achievement_load_progress
achievement_login
achievement_login_status
achievement_logout
achievement_map_achievement
achievement_map_leaderboard
achievement_post
achievement_post_score
achievement_reset
achievement_send_challenge
achievement_show
achievement_show_achievements
achievement_show_challenge_notifications
achievement_show_leaderboards
action_another_room
action_bounce
action_cd_pause
action_cd_play
action_cd_playing
action_cd_present
action_cd_resume
action_cd_stop
action_change_object
action_color
action_colour
action_create_object
action_create_object_motion
action_create_object_random
action_current_room
action_draw_arrow
action_draw_background
action_draw_ellipse
action_draw_ellipse_gradient
action_draw_font
action_draw_font_old
action_draw_gradient_hor
action_draw_gradient_vert
action_draw_health
action_draw_life
action_draw_life_images
action_draw_line
action_draw_rectangle
action_draw_score
action_draw_sprite
action_draw_text
action_draw_text_transformed
action_draw_variable
action_effect
action_end_game
action_end_sound
action_execute_script
action_fill_color
action_fill_colour
action_font
action_fullscreen
action_highscore
action_highscore_clear
action_highscore_show
action_if
action_if_aligned
action_if_collision
action_if_dice
action_if_empty
action_if_health
action_if_life
action_if_mouse
action_if_next_room
action_if_number
action_if_object
action_if_previous_room
action_if_question
action_if_score
action_if_sound
action_if_variable
action_inherited
action_kill_object
action_kill_position
action_line_color
action_line_colour
action_linear_step
action_load_game
action_message
action_move
action_move_contact
action_move_point
action_move_random
action_move_start
action_move_to
action_next_room
action_partemit_burst
action_partemit_create
action_partemit_destroy
action_partemit_stream
action_partsyst_clear
action_partsyst_create
action_partsyst_destroy
action_parttype_color
action_parttype_colour
action_parttype_create
action_parttype_create_old
action_parttype_gravity
action_parttype_life
action_parttype_secondary
action_parttype_speed
action_path
action_path_end
action_path_old
action_path_position
action_path_speed
action_potential_step
action_previous_room
action_replace_background
action_replace_sound
action_replace_sprite
action_restart_game
action_reverse_xdir
action_reverse_ydir
action_save_game
action_set_alarm
action_set_caption
action_set_cursor
action_set_friction
action_set_gravity
action_set_health
action_set_hspeed
action_set_life
action_set_motion
action_set_relative
action_set_score
action_set_sprite
action_set_timeline
action_set_timeline_position
action_set_timeline_speed
action_set_vspeed
action_show_info
action_show_video
action_sleep
action_snap
action_snapshot
action_sound
action_sprite_color
action_sprite_colour
action_sprite_set
action_sprite_transform
action_timeline_pause
action_timeline_set
action_timeline_start
action_timeline_stop
action_webpage
action_wrap
ads_disable
ads_enable
ads_engagement_active
ads_engagement_available
ads_engagement_launch
ads_event
ads_event_preload
ads_get_display_height
ads_get_display_width
ads_interstitial_available
ads_interstitial_display
ads_move
ads_set_reward_callback
ads_setup
alarm_get
alarm_set
analytics_event
analytics_event_ext
angle_difference
ansi_char
application_get_position
application_surface_draw_enable
application_surface_enable
application_surface_is_enabled
arccos
arcsin
arctan
arctan2
array_copy
array_create
array_equals
array_get
array_get_2D
array_height_2d
array_length_1d
array_length_2d
array_set
array_set_2D
array_set_2D_post
array_set_2D_pre
array_set_post
array_set_pre
asset_get_index
asset_get_type
audio_channel_num
audio_create_buffer_sound
audio_create_play_queue
audio_create_stream
audio_create_sync_group
audio_debug
audio_delete
audio_destroy_stream
audio_destroy_sync_group
audio_emitter_create
audio_emitter_exists
audio_emitter_falloff
audio_emitter_free
audio_emitter_gain
audio_emitter_get_gain
audio_emitter_get_listener_mask
audio_emitter_get_pitch
audio_emitter_get_vx
audio_emitter_get_vy
audio_emitter_get_vz
audio_emitter_get_x
audio_emitter_get_y
audio_emitter_get_z
audio_emitter_pitch
audio_emitter_position
audio_emitter_set_listener_mask
audio_emitter_velocity
audio_exists
audio_falloff_set_model
audio_free_buffer_sound
audio_free_play_queue
audio_get_listener_count
audio_get_listener_info
audio_get_listener_mask
audio_get_master_gain
audio_get_name
audio_get_recorder_count
audio_get_recorder_info
audio_get_type
audio_group_is_loaded
audio_group_load
audio_group_load_progress
audio_group_name
audio_group_set_gain
audio_group_stop_all
audio_group_unload
audio_is_paused
audio_is_playing
audio_listener_get_data
audio_listener_orientation
audio_listener_position
audio_listener_set_orientation
audio_listener_set_position
audio_listener_set_velocity
audio_listener_velocity
audio_master_gain
audio_music_gain
audio_music_is_playing
audio_pause_all
audio_pause_music
audio_pause_sound
audio_pause_sync_group
audio_play_in_sync_group
audio_play_music
audio_play_sound
audio_play_sound_at
audio_play_sound_on
audio_queue_sound
audio_resume_all
audio_resume_music
audio_resume_sound
audio_resume_sync_group
audio_set_listener_mask
audio_set_master_gain
audio_sound_gain
audio_sound_get_gain
audio_sound_get_listener_mask
audio_sound_get_pitch
audio_sound_get_track_position
audio_sound_length
audio_sound_pitch
audio_sound_set_listener_mask
audio_sound_set_track_position
audio_start_recording
audio_start_sync_group
audio_stop_all
audio_stop_music
audio_stop_recording
audio_stop_sound
audio_stop_sync_group
audio_sync_group_debug
audio_sync_group_get_track_pos
audio_sync_group_is_playing
audio_system
background_add
background_add_alpha
background_add_background
background_assign
background_create_color
background_create_colour
background_create_from_screen
background_create_from_surface
background_create_gradient
background_delete
background_duplicate
background_exists
background_flush
background_flush_multi
background_get_height
background_get_name
background_get_preload
background_get_smooth
background_get_texture
background_get_transparent
background_get_uvs
background_get_width
background_name
background_prefetch
background_prefetch_multi
background_replace
background_save
background_set_alpha_from_background
base64_decode
base64_encode
bool
browser_input_capture
buffer_async_group_begin
buffer_async_group_end
buffer_async_group_option
buffer_base64_decode
buffer_base64_decode_ext
buffer_base64_encode
buffer_compress
buffer_copy
buffer_copy_from_vertex_buffer
buffer_create
buffer_create_from_vertex_buffer
buffer_create_from_vertex_buffer_ext
buffer_decompress
buffer_delete
buffer_exists
buffer_fill
buffer_get_address
buffer_get_alignment
buffer_get_size
buffer_get_surface
buffer_get_type
buffer_load
buffer_load_async
buffer_load_ext
buffer_load_partial
buffer_md5
buffer_peek
buffer_poke
buffer_read
buffer_resize
buffer_save
buffer_save_async
buffer_save_ext
buffer_seek
buffer_set_surface
buffer_sha1
buffer_sizeof
buffer_tell
buffer_write
camera_apply
camera_create
camera_create_view
camera_destroy
camera_get_active
camera_get_begin_script
camera_get_default
camera_get_end_script
camera_get_proj_mat
camera_get_update_script
camera_get_view_angle
camera_get_view_border_x
camera_get_view_border_y
camera_get_view_height
camera_get_view_mat
camera_get_view_speed_x
camera_get_view_speed_y
camera_get_view_target
camera_get_view_width
camera_get_view_x
camera_get_view_y
camera_set_begin_script
camera_set_default
camera_set_end_script
camera_set_proj_mat
camera_set_update_script
camera_set_view_angle
camera_set_view_border
camera_set_view_mat
camera_set_view_pos
camera_set_view_size
camera_set_view_speed
camera_set_view_target
cd_close_door
cd_init
cd_length
cd_number
cd_open_door
cd_pause
cd_paused
cd_play
cd_playing
cd_position
cd_present
cd_resume
cd_set_position
cd_set_track_position
cd_stop
cd_track
cd_track_length
cd_track_position
ceil
choose
chr
clamp
clickable_add
clickable_add_ext
clickable_change
clickable_change_ext
clickable_delete
clickable_exists
clickable_set_style
clipboard_get_text
clipboard_has_text
clipboard_set_text
cloud_file_save
cloud_string_save
cloud_synchronise
code_is_compiled
collision_circle
collision_circle_list
collision_ellipse
collision_ellipse_list
collision_line
collision_line_list
collision_point
collision_point_list
collision_rectangle
collision_rectangle_list
collision_shape
color_get_blue
color_get_green
color_get_hue
color_get_red
color_get_saturation
color_get_value
colour_get_blue
colour_get_green
colour_get_hue
colour_get_red
colour_get_saturation
colour_get_value
cos
d3d_draw_block
d3d_draw_cone
d3d_draw_cylinder
d3d_draw_ellipsoid
d3d_draw_floor
d3d_draw_wall
d3d_end
d3d_light_define_ambient
d3d_light_define_direction
d3d_light_define_point
d3d_light_enable
d3d_model_block
d3d_model_clear
d3d_model_cone
d3d_model_create
d3d_model_cylinder
d3d_model_destroy
d3d_model_draw
d3d_model_ellipsoid
d3d_model_floor
d3d_model_load
d3d_model_load_buffer
d3d_model_primitive_begin
d3d_model_primitive_end
d3d_model_save
d3d_model_save_buffer
d3d_model_vertex
d3d_model_vertex_color
d3d_model_vertex_colour
d3d_model_vertex_normal
d3d_model_vertex_normal_color
d3d_model_vertex_normal_colour
d3d_model_vertex_normal_texture
d3d_model_vertex_normal_texture_color
d3d_model_vertex_normal_texture_colour
d3d_model_vertex_texture
d3d_model_vertex_texture_color
d3d_model_vertex_texture_colour
d3d_model_wall
d3d_primitive_begin
d3d_primitive_begin_texture
d3d_primitive_end
d3d_set_culling
d3d_set_depth
d3d_set_fog
d3d_set_hidden
d3d_set_lighting
d3d_set_perspective
d3d_set_projection
d3d_set_projection_ext
d3d_set_projection_ortho
d3d_set_projection_perspective
d3d_set_shading
d3d_set_zwriteenable
d3d_start
d3d_transform_add_rotation_axis
d3d_transform_add_rotation_x
d3d_transform_add_rotation_y
d3d_transform_add_rotation_z
d3d_transform_add_scaling
d3d_transform_add_translation
d3d_transform_set_identity
d3d_transform_set_rotation_axis
d3d_transform_set_rotation_x
d3d_transform_set_rotation_y
d3d_transform_set_rotation_z
d3d_transform_set_scaling
d3d_transform_set_translation
d3d_transform_stack_clear
d3d_transform_stack_discard
d3d_transform_stack_empty
d3d_transform_stack_pop
d3d_transform_stack_push
d3d_transform_stack_top
d3d_transform_vertex
d3d_vertex
d3d_vertex_color
d3d_vertex_colour
d3d_vertex_normal
d3d_vertex_normal_color
d3d_vertex_normal_colour
d3d_vertex_normal_texture
d3d_vertex_normal_texture_color
d3d_vertex_normal_texture_colour
d3d_vertex_texture
d3d_vertex_texture_color
d3d_vertex_texture_colour
darccos
darcsin
darctan
darctan2
date_compare_date
date_compare_datetime
date_compare_time
date_create_date
date_create_datetime
date_create_time
date_current_date
date_current_datetime
date_current_time
date_date_of
date_date_string
date_datetime_string
date_day_span
date_days_in_month
date_days_in_year
date_get_day
date_get_day_of_year
date_get_hour
date_get_hour_of_year
date_get_minute
date_get_minute_of_year
date_get_month
date_get_second
date_get_second_of_year
date_get_timezone
date_get_week
date_get_weekday
date_get_year
date_hour_span
date_inc_day
date_inc_hour
date_inc_minute
date_inc_month
date_inc_second
date_inc_week
date_inc_year
date_is_today
date_leap_year
date_minute_span
date_month_span
date_second_span
date_set_timezone
date_time_of
date_time_string
date_valid_date
date_valid_datetime
date_valid_time
date_week_span
date_year_span
dcos
debug_event
debug_get_callstack
degtorad
device_get_tilt_x
device_get_tilt_y
device_get_tilt_z
device_is_keypad_open
device_mouse_check_button
device_mouse_check_button_pressed
device_mouse_check_button_released
device_mouse_dbclick_enable
device_mouse_raw_x
device_mouse_raw_y
device_mouse_x
device_mouse_x_to_gui
device_mouse_y
device_mouse_y_to_gui
directory_create
directory_destroy
directory_exists
display_get_colordepth
display_get_dpi_x
display_get_dpi_y
display_get_frequency
display_get_gui_height
display_get_gui_width
display_get_height
display_get_orientation
display_get_sleep_margin
display_get_timing_method
display_get_width
display_get_windows_alternate_sync
display_get_windows_vertex_buffer_method
display_mouse_get_x
display_mouse_get_y
display_mouse_set
display_reset
display_set_all
display_set_colordepth
display_set_frequency
display_set_gui_maximise
display_set_gui_maximize
display_set_gui_size
display_set_size
display_set_sleep_margin
display_set_timing_method
display_set_ui_visibility
display_set_windows_alternate_sync
display_set_windows_vertex_buffer_method
display_test_all
distance_to_object
distance_to_point
dot_product
dot_product_3d
dot_product_3d_normalised
dot_product_3d_normalized
dot_product_normalised
dot_product_normalized
draw_arrow
draw_background
draw_background_ext
draw_background_general
draw_background_part
draw_background_part_ext
draw_background_stretched
draw_background_stretched_ext
draw_background_tiled
draw_background_tiled_ext
draw_button
draw_circle
draw_circle_color
draw_circle_colour
draw_clear
draw_clear_alpha
draw_ellipse
draw_ellipse_color
draw_ellipse_colour
draw_enable_alphablend
draw_enable_drawevent
draw_enable_swf_aa
draw_flush
draw_get_alpha
draw_get_alpha_test
draw_get_alpha_test_ref_value
draw_get_color
draw_get_colour
draw_get_lighting
draw_get_swf_aa_level
draw_getpixel
draw_getpixel_ext
draw_healthbar
draw_highscore
draw_light_define_ambient
draw_light_define_direction
draw_light_define_point
draw_light_enable
draw_light_get
draw_light_get_ambient
draw_line
draw_line_color
draw_line_colour
draw_line_width
draw_line_width_color
draw_line_width_colour
draw_path
draw_point
draw_point_color
draw_point_colour
draw_primitive_begin
draw_primitive_begin_texture
draw_primitive_end
draw_rectangle
draw_rectangle_color
draw_rectangle_colour
draw_roundrect
draw_roundrect_color
draw_roundrect_color_ext
draw_roundrect_colour
draw_roundrect_colour_ext
draw_roundrect_ext
draw_self
draw_set_alpha
draw_set_alpha_test
draw_set_alpha_test_ref_value
draw_set_blend_mode
draw_set_blend_mode_ext
draw_set_circle_precision
draw_set_color
draw_set_color_write_enable
draw_set_colour
draw_set_colour_write_enable
draw_set_font
draw_set_halign
draw_set_lighting
draw_set_swf_aa_level
draw_set_valign
draw_shape
draw_shape_string
draw_skeleton
draw_skeleton_collision
draw_skeleton_instance
draw_skeleton_time
draw_sprite
draw_sprite_ext
draw_sprite_general
draw_sprite_part
draw_sprite_part_ext
draw_sprite_pos
draw_sprite_stretched
draw_sprite_stretched_ext
draw_sprite_tiled
draw_sprite_tiled_ext
draw_surface
draw_surface_ext
draw_surface_general
draw_surface_part
draw_surface_part_ext
draw_surface_stretched
draw_surface_stretched_ext
draw_surface_tiled
draw_surface_tiled_ext
draw_text
draw_text_color
draw_text_colour
draw_text_ext
draw_text_ext_color
draw_text_ext_colour
draw_text_ext_transformed
draw_text_ext_transformed_color
draw_text_ext_transformed_colour
draw_text_transformed
draw_text_transformed_color
draw_text_transformed_colour
draw_texture_flush
draw_tile
draw_tilemap
draw_triangle
draw_triangle_color
draw_triangle_colour
draw_vertex
draw_vertex_color
draw_vertex_colour
draw_vertex_texture
draw_vertex_texture_color
draw_vertex_texture_colour
ds_exists
ds_grid_add
ds_grid_add_disk
ds_grid_add_grid_region
ds_grid_add_region
ds_grid_clear
ds_grid_copy
ds_grid_create
ds_grid_destroy
ds_grid_get
ds_grid_get_disk_max
ds_grid_get_disk_mean
ds_grid_get_disk_min
ds_grid_get_disk_sum
ds_grid_get_max
ds_grid_get_mean
ds_grid_get_min
ds_grid_get_sum
ds_grid_height
ds_grid_multiply
ds_grid_multiply_disk
ds_grid_multiply_grid_region
ds_grid_multiply_region
ds_grid_read
ds_grid_resize
ds_grid_set
ds_grid_set_disk
ds_grid_set_grid_region
ds_grid_set_post
ds_grid_set_pre
ds_grid_set_region
ds_grid_shuffle
ds_grid_sort
ds_grid_value_disk_exists
ds_grid_value_disk_x
ds_grid_value_disk_y
ds_grid_value_exists
ds_grid_value_x
ds_grid_value_y
ds_grid_width
ds_grid_write
ds_list_add
ds_list_clear
ds_list_copy
ds_list_create
ds_list_delete
ds_list_destroy
ds_list_empty
ds_list_find_index
ds_list_find_value
ds_list_insert
ds_list_mark_as_list
ds_list_mark_as_map
ds_list_read
ds_list_replace
ds_list_set
ds_list_set_post
ds_list_set_pre
ds_list_shuffle
ds_list_size
ds_list_sort
ds_list_write
ds_map_add
ds_map_add_list
ds_map_add_map
ds_map_clear
ds_map_copy
ds_map_create
ds_map_delete
ds_map_destroy
ds_map_empty
ds_map_exists
ds_map_find_first
ds_map_find_last
ds_map_find_next
ds_map_find_previous
ds_map_find_value
ds_map_read
ds_map_replace
ds_map_replace_list
ds_map_replace_map
ds_map_secure_load
ds_map_secure_load_buffer
ds_map_secure_save
ds_map_secure_save_buffer
ds_map_set
ds_map_set_post
ds_map_set_pre
ds_map_size
ds_map_write
ds_priority_add
ds_priority_change_priority
ds_priority_clear
ds_priority_copy
ds_priority_create
ds_priority_delete_max
ds_priority_delete_min
ds_priority_delete_value
ds_priority_destroy
ds_priority_empty
ds_priority_find_max
ds_priority_find_min
ds_priority_find_priority
ds_priority_read
ds_priority_size
ds_priority_write
ds_queue_clear
ds_queue_copy
ds_queue_create
ds_queue_dequeue
ds_queue_destroy
ds_queue_empty
ds_queue_enqueue
ds_queue_head
ds_queue_read
ds_queue_size
ds_queue_tail
ds_queue_write
ds_set_precision
ds_stack_clear
ds_stack_copy
ds_stack_create
ds_stack_destroy
ds_stack_empty
ds_stack_pop
ds_stack_push
ds_stack_read
ds_stack_size
ds_stack_top
ds_stack_write
dsin
dtan
effect_clear
effect_create_above
effect_create_below
environment_get_variable
ERROR
event_inherited
event_perform
event_perform_object
event_user
execute_program
execute_shell
exp
extension_stubfunc_real
extension_stubfunc_string
external_call
external_call0
external_call1
external_call2
external_call3
external_call4
external_call5
external_call6
external_call7
external_call8
external_define
external_define0
external_define1
external_define2
external_define3
external_define4
external_define5
external_define6
external_define7
external_define8
external_free
F_GPIO_Set_Function
facebook_accesstoken
facebook_check_permission
facebook_dialog
facebook_graph_request
facebook_init
facebook_launch_offerwall
facebook_login
facebook_logout
facebook_post_message
facebook_request_publish_permissions
facebook_request_read_permissions
facebook_send_invite
facebook_status
facebook_user_id
file_attributes
file_bin_close
file_bin_open
file_bin_position
file_bin_read_byte
file_bin_rewrite
file_bin_seek
file_bin_size
file_bin_write_byte
file_close
file_copy
file_delete
file_eof
file_exists
file_find_close
file_find_first
file_find_next
file_open_append
file_open_read
file_open_write
file_read_real
file_read_string
file_readln
file_rename
file_text_close
file_text_eof
file_text_eoln
file_text_open_append
file_text_open_from_string
file_text_open_read
file_text_open_write
file_text_read_real
file_text_read_string
file_text_readln
file_text_write_real
file_text_write_string
file_text_writeln
file_write_real
file_write_string
file_writeln
filename_change_ext
filename_dir
filename_drive
filename_ext
filename_name
filename_path
floor
font_add
font_add_enable_aa
font_add_get_enable_aa
font_add_sprite
font_add_sprite_ext
font_delete
font_exists
font_get_bold
font_get_dynamic_texture_size
font_get_first
font_get_fontname
font_get_italic
font_get_last
font_get_name
font_get_size
font_get_texture
font_get_uvs
font_name
font_replace_sprite
font_replace_sprite_ext
font_set_cache_size
font_set_dynamic_texture_size
frac
frustum_build
frustum_test_sphere
game_end
game_get_speed
game_load
game_load_buffer
game_restart
game_save
game_save_buffer
game_set_speed
gamepad_add_hardware_mapping_from_file
gamepad_add_hardware_mapping_from_string
gamepad_axis_count
gamepad_axis_value
gamepad_button_check
gamepad_button_check_pressed
gamepad_button_check_released
gamepad_button_count
gamepad_button_value
gamepad_get_axis_deadzone
gamepad_get_button_threshold
gamepad_get_description
gamepad_get_device_count
gamepad_get_hardware_mappings
gamepad_is_connected
gamepad_is_supported
gamepad_set_axis_deadzone
gamepad_set_button_threshold
gamepad_set_color
gamepad_set_colour
gamepad_set_vibration
gesture_double_tap_distance
gesture_double_tap_time
gesture_drag_distance
gesture_drag_time
gesture_flick_speed
gesture_get_double_tap_distance
gesture_get_double_tap_time
gesture_get_drag_distance
gesture_get_drag_time
gesture_get_flick_speed
gesture_get_pinch_angle_away
gesture_get_pinch_angle_towards
gesture_get_pinch_distance
gesture_get_rotate_angle
gesture_get_rotate_time
gesture_get_tap_count
gesture_pinch_angle_away
gesture_pinch_angle_towards
gesture_pinch_distance
gesture_rotate_angle
gesture_rotate_time
gesture_tap_count
get_color
get_directory
get_directory_alt
get_integer
get_integer_async
get_login_async
get_open_filename
get_open_filename_ext
get_save_filename
get_save_filename_ext
get_string
get_string_async
get_timer
gml_release_mode
gpio_clear
gpio_get
gpio_set
gpio_set_mode
gpu_get_alphatestenable
gpu_get_alphatestfunc
gpu_get_alphatestref
gpu_get_blendenable
gpu_get_blendmode
gpu_get_blendmode_dest
gpu_get_blendmode_destalpha
gpu_get_blendmode_ext
gpu_get_blendmode_ext_sepalpha
gpu_get_blendmode_src
gpu_get_blendmode_srcalpha
gpu_get_colorwriteenable
gpu_get_colourwriteenable
gpu_get_cullmode
gpu_get_fog
gpu_get_state
gpu_get_tex_filter
gpu_get_tex_filter_ext
gpu_get_tex_max_aniso
gpu_get_tex_max_aniso_ext
gpu_get_tex_max_mip
gpu_get_tex_max_mip_ext
gpu_get_tex_min_mip
gpu_get_tex_min_mip_ext
gpu_get_tex_mip_bias
gpu_get_tex_mip_bias_ext
gpu_get_tex_mip_enable
gpu_get_tex_mip_enable_ext
gpu_get_tex_mip_filter
gpu_get_tex_mip_filter_ext
gpu_get_tex_repeat
gpu_get_tex_repeat_ext
gpu_get_texfilter
gpu_get_texfilter_ext
gpu_get_texrepeat
gpu_get_texrepeat_ext
gpu_get_zfunc
gpu_get_ztestenable
gpu_get_zwriteenable
gpu_pop_state
gpu_push_state
gpu_set_alphatestenable
gpu_set_alphatestfunc
gpu_set_alphatestref
gpu_set_blendenable
gpu_set_blendmode
gpu_set_blendmode_ext
gpu_set_blendmode_ext_sepalpha
gpu_set_colorwriteenable
gpu_set_colourwriteenable
gpu_set_cullmode
gpu_set_fog
gpu_set_state
gpu_set_tex_filter
gpu_set_tex_filter_ext
gpu_set_tex_max_aniso
gpu_set_tex_max_aniso_ext
gpu_set_tex_max_mip
gpu_set_tex_max_mip_ext
gpu_set_tex_min_mip
gpu_set_tex_min_mip_ext
gpu_set_tex_mip_bias
gpu_set_tex_mip_bias_ext
gpu_set_tex_mip_enable
gpu_set_tex_mip_enable_ext
gpu_set_tex_mip_filter
gpu_set_tex_mip_filter_ext
gpu_set_tex_repeat
gpu_set_tex_repeat_ext
gpu_set_texfilter
gpu_set_texfilter_ext
gpu_set_texrepeat
gpu_set_texrepeat_ext
gpu_set_zfunc
gpu_set_ztestenable
gpu_set_zwriteenable
highscore_add
highscore_add_current
highscore_clear
highscore_name
highscore_set_background
highscore_set_border
highscore_set_colors
highscore_set_font
highscore_set_strings
highscore_show
highscore_show_ext
highscore_value
http_get
http_get_file
http_post_string
http_request
iap_acquire
iap_activate
iap_consume
iap_enumerate_products
iap_event_queue
iap_files_purchased
iap_is_downloaded
iap_is_purchased
iap_product_details
iap_product_files
iap_product_status
iap_purchase_details
iap_restore_all
iap_status
iap_store_status
ini_close
ini_key_delete
ini_key_exists
ini_open
ini_open_from_string
ini_read_real
ini_read_string
ini_section_delete
ini_section_exists
ini_write_real
ini_write_string
instance_activate_all
instance_activate_layer
instance_activate_object
instance_activate_region
instance_change
instance_copy
instance_create
instance_create_depth
instance_create_layer
instance_deactivate_all
instance_deactivate_layer
instance_deactivate_object
instance_deactivate_region
instance_deactivate_region_special
instance_destroy
instance_exists
instance_find
instance_furthest
instance_id_get
instance_nearest
instance_number
instance_place
instance_place_list
instance_position
instance_position_list
instance_sprite
int64
io_clear
io_handle
irandom
irandom_range
is_array
is_bool
is_int32
is_int64
is_matrix
is_ptr
is_real
is_string
is_undefined
is_vec3
is_vec4
joystick_axes
joystick_buttons
joystick_check_button
joystick_direction
joystick_exists
joystick_has_pov
joystick_name
joystick_pov
joystick_rpos
joystick_upos
joystick_vpos
joystick_xpos
joystick_ypos
joystick_zpos
json_decode
json_encode
keyboard_check
keyboard_check_direct
keyboard_check_pressed
keyboard_check_released
keyboard_clear
keyboard_get_map
keyboard_get_numlock
keyboard_key_press
keyboard_key_release
keyboard_set_map
keyboard_set_numlock
keyboard_unset_map
keyboard_virtual_height
keyboard_virtual_hide
keyboard_virtual_show
keyboard_virtual_status
keyboard_wait
layer_add_instance
layer_background_alpha
layer_background_blend
layer_background_change
layer_background_create
layer_background_destroy
layer_background_exists
layer_background_get_alpha
layer_background_get_blend
layer_background_get_htiled
layer_background_get_id
layer_background_get_index
layer_background_get_speed
layer_background_get_sprite
layer_background_get_stretch
layer_background_get_visible
layer_background_get_vtiled
layer_background_get_xscale
layer_background_get_yscale
layer_background_htiled
layer_background_index
layer_background_speed
layer_background_sprite
layer_background_stretch
layer_background_visible
layer_background_vtiled
layer_background_xscale
layer_background_yscale
layer_create
layer_depth
layer_destroy
layer_destroy_instances
layer_element_move
layer_exists
layer_force_draw_depth
layer_get_all
layer_get_all_elements
layer_get_depth
layer_get_element_layer
layer_get_element_type
layer_get_forced_depth
layer_get_hspeed
layer_get_id
layer_get_id_at_depth
layer_get_name
layer_get_script_begin
layer_get_script_end
layer_get_shader
layer_get_target_room
layer_get_visible
layer_get_vspeed
layer_get_x
layer_get_y
layer_has_instance
layer_hspeed
layer_instance_get_instance
layer_is_draw_depth_forced
layer_reset_target_room
layer_script_begin
layer_script_end
layer_set_target_room
layer_set_visible
layer_shader
layer_sprite_alpha
layer_sprite_angle
layer_sprite_blend
layer_sprite_change
layer_sprite_create
layer_sprite_destroy
layer_sprite_exists
layer_sprite_get_alpha
layer_sprite_get_angle
layer_sprite_get_blend
layer_sprite_get_id
layer_sprite_get_index
layer_sprite_get_speed
layer_sprite_get_sprite
layer_sprite_get_x
layer_sprite_get_xscale
layer_sprite_get_y
layer_sprite_get_yscale
layer_sprite_index
layer_sprite_speed
layer_sprite_x
layer_sprite_xscale
layer_sprite_y
layer_sprite_yscale
layer_tile_alpha
layer_tile_blend
layer_tile_change
layer_tile_create
layer_tile_destroy
layer_tile_exists
layer_tile_get_alpha
layer_tile_get_blend
layer_tile_get_region
layer_tile_get_sprite
layer_tile_get_visible
layer_tile_get_x
layer_tile_get_xscale
layer_tile_get_y
layer_tile_get_yscale
layer_tile_region
layer_tile_visible
layer_tile_x
layer_tile_xscale
layer_tile_y
layer_tile_yscale
layer_tilemap_create
layer_tilemap_destroy
layer_tilemap_exists
layer_tilemap_get_id
layer_vspeed
layer_x
layer_y
lengthdir_x
lengthdir_y
lerp
ln
load_csv
load_info
log10
log2
logn
make_color
make_color_hsv
make_color_rgb
make_colour
make_colour_hsv
make_colour_rgb
matchmaking_add_create_param
matchmaking_add_find_param
matchmaking_join_invite
matchmaking_reset_create_params
matchmaking_reset_find_params
matchmaking_send_invites
matchmaking_send_invites_no_ui
matchmaking_session_create
matchmaking_session_find
matchmaking_session_get_owner
matchmaking_session_get_users
matchmaking_session_invite_start
matchmaking_session_join
matchmaking_session_leave
matchmaking_session_set_closed
matchmaking_session_set_hidden
matchmaking_session_set_open
matchmaking_session_update
matchmaking_start
matchmaking_stop
matchmaking_tick_invites
math_get_epsilon
math_set_epsilon
matrix_build
matrix_build_identity
matrix_build_lookat
matrix_build_projection_ortho
matrix_build_projection_perspective
matrix_build_projection_perspective_fov
matrix_get
matrix_multiply
matrix_set
matrix_stack_clear
matrix_stack_is_empty
matrix_stack_pop
matrix_stack_push
matrix_stack_set
matrix_stack_top
matrix_transform_vertex
max
max3
MCI_command
md5_file
md5_string_unicode
md5_string_utf8
mean
median
merge_color
merge_colour
message_alpha
message_background
message_button
message_button_font
message_caption
message_input_color
message_input_font
message_mouse_color
message_position
message_size
message_text_font
min
min3
motion_add
motion_set
mouse_check_button
mouse_check_button_pressed
mouse_check_button_released
mouse_clear
mouse_wait
mouse_wheel_down
mouse_wheel_up
move_bounce
move_bounce_all
move_bounce_solid
move_contact
move_contact_all
move_contact_solid
move_outside_all
move_outside_solid
move_random
move_snap
move_towards_point
move_wrap
mp_grid_add_cell
mp_grid_add_instances
mp_grid_add_rectangle
mp_grid_clear_all
mp_grid_clear_cell
mp_grid_clear_rectangle
mp_grid_create
mp_grid_destroy
mp_grid_draw
mp_grid_get_cell
mp_grid_path
mp_grid_to_ds_grid
mp_linear_path
mp_linear_path_object
mp_linear_step
mp_linear_step_object
mp_potential_path
mp_potential_path_object
mp_potential_settings
mp_potential_step
mp_potential_step_object
network_connect
network_connect_raw
network_create_server
network_create_server_raw
network_create_socket
network_create_socket_ext
network_destroy
network_resolve
network_send_broadcast
network_send_packet
network_send_raw
network_send_udp
network_send_udp_raw
network_set_config
network_set_timeout
object_add
object_delete
object_event_add
object_event_clear
object_exists
object_get_depth
object_get_mask
object_get_name
object_get_parent
object_get_persistent
object_get_physics
object_get_solid
object_get_sprite
object_get_visible
object_is_ancestor
object_name
object_set_collisions
object_set_depth
object_set_mask
object_set_parent
object_set_persistent
object_set_solid
object_set_sprite
object_set_visible
openfeint_accept_challenge
openfeint_send_challenge
openfeint_send_invite
openfeint_send_result
openfeint_send_social
openfeint_set_url
openfeint_start
ord
os_check_permission
os_get_config
os_get_info
os_get_language
os_get_region
os_is_network_connected
os_is_paused
os_lock_orientation
os_powersave_enable
os_request_permission
parameter_count
parameter_string
part_emitter_burst
part_emitter_clear
part_emitter_create
part_emitter_destroy
part_emitter_destroy_all
part_emitter_exists
part_emitter_region
part_emitter_stream
part_particles_clear
part_particles_count
part_particles_create
part_particles_create_color
part_particles_create_colour
part_system_automatic_draw
part_system_automatic_update
part_system_clear
part_system_create
part_system_create_layer
part_system_depth
part_system_destroy
part_system_draw_order
part_system_drawit
part_system_exists
part_system_get_layer
part_system_layer
part_system_position
part_system_update
part_type_alpha
part_type_alpha1
part_type_alpha2
part_type_alpha3
part_type_blend
part_type_clear
part_type_color
part_type_color_hsv
part_type_color_mix
part_type_color_rgb
part_type_color1
part_type_color2
part_type_color3
part_type_colour
part_type_colour_hsv
part_type_colour_mix
part_type_colour_rgb
part_type_colour1
part_type_colour2
part_type_colour3
part_type_create
part_type_death
part_type_destroy
part_type_direction
part_type_exists
part_type_gravity
part_type_life
part_type_orientation
part_type_scale
part_type_shape
part_type_size
part_type_speed
part_type_sprite
part_type_step
path_add
path_add_point
path_append
path_assign
path_change_point
path_clear_points
path_delete
path_delete_point
path_duplicate
path_end
path_exists
path_flip
path_get_closed
path_get_kind
path_get_length
path_get_name
path_get_number
path_get_point_speed
path_get_point_x
path_get_point_y
path_get_precision
path_get_speed
path_get_time
path_get_x
path_get_y
path_insert_point
path_mirror
path_name
path_rescale
path_reverse
path_rotate
path_set_closed
path_set_kind
path_set_precision
path_shift
path_start
physics_apply_angular_impulse
physics_apply_force
physics_apply_impulse
physics_apply_local_force
physics_apply_local_impulse
physics_apply_torque
physics_draw_debug
physics_fixture_add_point
physics_fixture_bind
physics_fixture_bind_ext
physics_fixture_create
physics_fixture_delete
physics_fixture_set_angular_damping
physics_fixture_set_awake
physics_fixture_set_box_shape
physics_fixture_set_chain_shape
physics_fixture_set_circle_shape
physics_fixture_set_collision_group
physics_fixture_set_density
physics_fixture_set_edge_shape
physics_fixture_set_friction
physics_fixture_set_kinematic
physics_fixture_set_linear_damping
physics_fixture_set_polygon_shape
physics_fixture_set_restitution
physics_fixture_set_sensor
physics_get_density
physics_get_friction
physics_get_restitution
physics_joint_delete
physics_joint_distance_create
physics_joint_enable_motor
physics_joint_friction_create
physics_joint_gear_create
physics_joint_get_value
physics_joint_prismatic_create
physics_joint_pulley_create
physics_joint_revolute_create
physics_joint_rope_create
physics_joint_set_value
physics_joint_weld_create
physics_joint_wheel_create
physics_mass_properties
physics_particle_count
physics_particle_create
physics_particle_delete
physics_particle_delete_region_box
physics_particle_delete_region_circle
physics_particle_delete_region_poly
physics_particle_draw
physics_particle_draw_ext
physics_particle_get_damping
physics_particle_get_data
physics_particle_get_data_particle
physics_particle_get_density
physics_particle_get_gravity_scale
physics_particle_get_group_flags
physics_particle_get_max_count
physics_particle_get_radius
physics_particle_group_add_point
physics_particle_group_begin
physics_particle_group_box
physics_particle_group_circle
physics_particle_group_count
physics_particle_group_delete
physics_particle_group_end
physics_particle_group_get_ang_vel
physics_particle_group_get_angle
physics_particle_group_get_centre_x
physics_particle_group_get_centre_y
physics_particle_group_get_data
physics_particle_group_get_inertia
physics_particle_group_get_mass
physics_particle_group_get_vel_x
physics_particle_group_get_vel_y
physics_particle_group_get_x
physics_particle_group_get_y
physics_particle_group_join
physics_particle_group_polygon
physics_particle_set_category_flags
physics_particle_set_damping
physics_particle_set_density
physics_particle_set_flags
physics_particle_set_gravity_scale
physics_particle_set_group_flags
physics_particle_set_max_count
physics_particle_set_radius
physics_pause_enable
physics_remove_fixture
physics_set_density
physics_set_friction
physics_set_restitution
physics_test_overlap
physics_world_create
physics_world_draw_debug
physics_world_gravity
physics_world_update_iterations
physics_world_update_speed
place_empty
place_free
place_meeting
place_snapped
point_direction
point_distance
point_distance_3d
point_in_circle
point_in_rectangle
point_in_triangle
position_change
position_destroy
position_empty
position_meeting
power
ps4_share_screenshot_enable
ps4_share_video_enable
psn_check_free_space
psn_check_np_availability
psn_content_restriction_add
psn_default_user
psn_default_user_name
psn_delete_tus_data
psn_exit_np_libs
psn_get_avatar_url
psn_get_entitlement_list
psn_get_friends_scores
psn_get_leaderboard_score
psn_get_leaderboard_score_range
psn_get_trophy_unlock_state
psn_get_tus_data
psn_get_tus_variable
psn_init_np_libs
psn_init_trophy
psn_load_modules
psn_name_for_pad
psn_name_for_user
psn_net_check
psn_np_check_plus
psn_np_commerce_dialog_open
psn_np_commerce_dialog_tick
psn_np_notify_plus_feature
psn_np_status
psn_post_leaderboard_score
psn_post_leaderboard_score_comment
psn_set_content_restriction
psn_set_tus_data
psn_set_tus_variable
psn_setup_trophies
psn_show_error_dialog
psn_tick
psn_tick_error_dialog
psn_unlock_trophy
psn_user_for_pad
ptr
push_cancel_local_notification
push_get_first_local_notification
push_get_next_local_notification
push_local_notification
radtodeg
random
random_get_seed
random_range
random_set_seed
random_use_old_version
randomise
randomize
real
rectangle_in_circle
rectangle_in_rectangle
rectangle_in_triangle
room_add
room_assign
room_duplicate
room_exists
room_get_camera
room_get_name
room_get_viewport
room_goto
room_goto_next
room_goto_previous
room_instance_add
room_instance_clear
room_name
room_next
room_previous
room_restart
room_set_background
room_set_background_color
room_set_background_colour
room_set_camera
room_set_caption
room_set_code
room_set_height
room_set_persistent
room_set_view
room_set_view_enabled
room_set_viewport
room_set_width
room_tile_add
room_tile_add_ext
room_tile_clear
round
screen_save
screen_save_part
script_execute
script_exists
script_get_name
script_get_text
set_application_title
set_program_priority
sha1_file
sha1_string_unicode
sha1_string_utf8
shader_current
shader_enable_corner_id
shader_get_name
shader_get_sampler_index
shader_get_uniform
shader_is_compiled
shader_reset
shader_set
shader_set_uniform_f
shader_set_uniform_f_array
shader_set_uniform_i
shader_set_uniform_i_array
shader_set_uniform_matrix
shader_set_uniform_matrix_array
shaders_are_supported
shop_leave_rating
show_debug_message
show_debug_overlay
show_error
show_image
show_info
show_menu
show_menu_pos
show_message
show_message_async
show_message_ext
show_question
show_question_async
show_text
show_video
sign
sin
skeleton_animation_clear
skeleton_animation_get
skeleton_animation_get_duration
skeleton_animation_get_ext
skeleton_animation_get_frame
skeleton_animation_get_frames
skeleton_animation_list
skeleton_animation_mix
skeleton_animation_set
skeleton_animation_set_ext
skeleton_animation_set_frame
skeleton_attachment_create
skeleton_attachment_get
skeleton_attachment_set
skeleton_bone_data_get
skeleton_bone_data_set
skeleton_bone_state_get
skeleton_bone_state_set
skeleton_collision_draw_set
skeleton_get_bounds
skeleton_get_minmax
skeleton_get_num_bounds
skeleton_skin_get
skeleton_skin_list
skeleton_skin_set
skeleton_slot_data
sleep
sound_3d_set_sound_cone
sound_3d_set_sound_distance
sound_3d_set_sound_position
sound_3d_set_sound_velocity
sound_add
sound_background_tempo
sound_delete
sound_discard
sound_effect_chorus
sound_effect_compressor
sound_effect_echo
sound_effect_equalizer
sound_effect_flanger
sound_effect_gargle
sound_effect_reverb
sound_effect_set
sound_exists
sound_fade
sound_get_kind
sound_get_name
sound_get_preload
sound_global_volume
sound_isplaying
sound_loop
sound_name
sound_pan
sound_play
sound_replace
sound_restore
sound_set_search_directory
sound_stop
sound_stop_all
sound_volume
splash_set_adapt
splash_set_border
splash_set_caption
splash_set_color
splash_set_cursor
splash_set_fullscreen
splash_set_interrupt
splash_set_main
splash_set_scale
splash_set_size
splash_set_stop_key
splash_set_stop_mouse
splash_set_top
splash_show_image
splash_show_text
splash_show_video
sprite_add
sprite_add_alpha
sprite_add_from_screen
sprite_add_from_surface
sprite_add_sprite
sprite_assign
sprite_collision_mask
sprite_create_from_screen
sprite_create_from_surface
sprite_delete
sprite_duplicate
sprite_exists
sprite_flush
sprite_flush_multi
sprite_get_bbox_bottom
sprite_get_bbox_left
sprite_get_bbox_mode
sprite_get_bbox_right
sprite_get_bbox_top
sprite_get_height
sprite_get_name
sprite_get_number
sprite_get_precise
sprite_get_preload
sprite_get_smooth
sprite_get_speed
sprite_get_speed_type
sprite_get_texture
sprite_get_tpe
sprite_get_transparent
sprite_get_uvs
sprite_get_width
sprite_get_xoffset
sprite_get_yoffset
sprite_merge
sprite_name
sprite_prefetch
sprite_prefetch_multi
sprite_replace
sprite_replace_sprite
sprite_save
sprite_set_alpha_from_sprite
sprite_set_bbox
sprite_set_bbox_mode
sprite_set_cache_size
sprite_set_cache_size_ext
sprite_set_offset
sprite_set_precise
sprite_set_speed
sqr
sqrt
steam_activate_overlay
steam_activate_overlay_browser
steam_activate_overlay_store
steam_activate_overlay_user
steam_available_languages
steam_clear_achievement
steam_create_leaderboard
steam_current_game_language
steam_download_friends_scores
steam_download_scores
steam_download_scores_around_user
steam_file_delete
steam_file_exists
steam_file_persisted
steam_file_read
steam_file_share
steam_file_size
steam_file_write
steam_file_write_file
steam_get_achievement
steam_get_app_id
steam_get_persona_name
steam_get_quota_free
steam_get_quota_total
steam_get_stat_avg_rate
steam_get_stat_float
steam_get_stat_int
steam_get_user_account_id
steam_get_user_persona_name
steam_get_user_steam_id
steam_initialised
steam_is_cloud_enabled_for_account
steam_is_cloud_enabled_for_app
steam_is_overlay_activated
steam_is_overlay_enabled
steam_is_screenshot_requested
steam_is_user_logged_on
steam_publish_workshop_file
steam_reset_all_stats
steam_reset_all_stats_achievements
steam_send_screenshot
steam_set_achievement
steam_set_stat_avg_rate
steam_set_stat_float
steam_set_stat_int
steam_stats_ready
steam_ugc_create_item
steam_ugc_create_query_all
steam_ugc_create_query_all_ex
steam_ugc_create_query_user
steam_ugc_create_query_user_ex
steam_ugc_download
steam_ugc_get_item_install_info
steam_ugc_get_item_update_info
steam_ugc_get_item_update_progress
steam_ugc_get_subscribed_items
steam_ugc_num_subscribed_items
steam_ugc_query_add_excluded_tag
steam_ugc_query_add_required_tag
steam_ugc_query_set_allow_cached_response
steam_ugc_query_set_cloud_filename_filter
steam_ugc_query_set_match_any_tag
steam_ugc_query_set_ranked_by_trend_days
steam_ugc_query_set_return_long_description
steam_ugc_query_set_return_total_only
steam_ugc_query_set_search_text
steam_ugc_request_item_details
steam_ugc_send_query
steam_ugc_set_item_content
steam_ugc_set_item_description
steam_ugc_set_item_preview
steam_ugc_set_item_tags
steam_ugc_set_item_title
steam_ugc_set_item_visibility
steam_ugc_start_item_update
steam_ugc_submit_item_update
steam_ugc_subscribe_item
steam_ugc_unsubscribe_item
steam_upload_score
steam_upload_score_buffer
steam_upload_score_buffer_ext
steam_upload_score_ext
steam_user_installed_dlc
steam_user_owns_dlc
string
string_byte_at
string_byte_length
string_char_at
string_copy
string_count
string_delete
string_digits
string_format
string_hash_to_newline
string_height
string_height_ext
string_insert
string_length
string_letters
string_lettersdigits
string_lower
string_ord_at
string_pos
string_repeat
string_replace
string_replace_all
string_set_byte_at
string_upper
string_width
string_width_ext
surface_copy
surface_copy_part
surface_create
surface_create_ext
surface_create_special
surface_depth_disable
surface_exists
surface_free
surface_get_depth_disable
surface_get_height
surface_get_texture
surface_get_width
surface_getpixel
surface_getpixel_ext
surface_reset_target
surface_resize
surface_save
surface_save_part
surface_set_target
surface_set_target_ext
switch_accounts_close_user
switch_accounts_get_accounts
switch_accounts_get_nickname
switch_accounts_is_user_open
switch_accounts_login_user
switch_accounts_open_user
switch_accounts_select_account
switch_add_ssl_certificate
switch_bnvib_get_length
switch_bnvib_get_loop_end_position
switch_bnvib_get_loop_interval
switch_bnvib_get_loop_start_position
switch_bnvib_get_sampling_rate
switch_bnvib_get_value
switch_bnvib_is_looping
switch_bnvib_load
switch_bnvib_unload
switch_controller_acceleration
switch_controller_angle
switch_controller_angular_velocity
switch_controller_direction
switch_controller_get_handheld_activation_mode
switch_controller_get_supported_styles
switch_controller_is_at_rest
switch_controller_joycon_get_holdtype
switch_controller_joycon_left_connected
switch_controller_joycon_right_connected
switch_controller_joycon_set_holdtype
switch_controller_set_handheld_activation_mode
switch_controller_set_supported_styles
switch_controller_show_strap_guide
switch_controller_support_get_player_count
switch_controller_support_get_selected_id
switch_controller_support_set_all
switch_controller_support_set_defaults
switch_controller_support_set_explain_text
switch_controller_support_set_left_justify
switch_controller_support_set_maintain_connections
switch_controller_support_set_permit_joycon_dual
switch_controller_support_set_player_max
switch_controller_support_set_player_min
switch_controller_support_set_show_explain_text
switch_controller_support_set_show_identification_colors
switch_controller_support_set_show_identification_colours
switch_controller_support_set_singleplayer_only
switch_controller_support_show
switch_controller_vibrate_hd
switch_controller_vibration_permitted
switch_get_operation_mode
switch_get_performance_config
switch_get_performance_mode
switch_irsensor_cluster_config_set_defaults
switch_irsensor_cluster_config_set_external_light_filtering
switch_irsensor_cluster_config_set_object_intensity_min
switch_irsensor_cluster_config_set_object_pixel_count_max
switch_irsensor_cluster_config_set_object_pixel_count_min
switch_irsensor_cluster_config_set_window_of_interest
switch_irsensor_cluster_create_state_buffer
switch_irsensor_common_config_is_negative_image_used
switch_irsensor_common_config_set_all
switch_irsensor_common_config_set_exposure_time
switch_irsensor_common_config_set_gain
switch_irsensor_common_config_set_light_target
switch_irsensor_get_ambient_noise_level
switch_irsensor_hand_config_set_mode
switch_irsensor_hand_create_state_buffers
switch_irsensor_image_config_set_defaults
switch_irsensor_image_config_set_external_light_filtering
switch_irsensor_image_config_set_format
switch_irsensor_image_config_set_orig_format
switch_irsensor_image_config_set_trimming_format
switch_irsensor_image_config_set_trimming_start
switch_irsensor_image_create_state_buffers
switch_irsensor_moment_config_set_defaults
switch_irsensor_moment_config_set_preprocess
switch_irsensor_moment_config_set_preprocess_intensity_threshold
switch_irsensor_moment_config_set_window_of_interest
switch_irsensor_moment_create_state_buffer
switch_irsensor_set_mode
switch_language_get_desired_language
switch_recording_disable
switch_recording_enable
switch_save_data_commit
switch_save_data_mount
switch_save_data_unmount
switch_screenshot_disable
switch_screenshot_enable
switch_screenshot_set_orientation
switch_set_local_network_mode
switch_set_performance_config
switch_theme_set
tan
testFailed
texture_exists
texture_get_height
texture_get_texel_height
texture_get_texel_width
texture_get_uvs
texture_get_width
texture_global_scale
texture_preload
texture_set_blending
texture_set_interpolation
texture_set_interpolation_ext
texture_set_priority
texture_set_repeat
texture_set_repeat_ext
texture_set_stage
tile_add
tile_delete
tile_exists
tile_get_alpha
tile_get_background
tile_get_blend
tile_get_count
tile_get_depth
tile_get_empty
tile_get_flip
tile_get_height
tile_get_id
tile_get_ids
tile_get_ids_at_depth
tile_get_index
tile_get_left
tile_get_mirror
tile_get_rotate
tile_get_top
tile_get_visible
tile_get_width
tile_get_x
tile_get_xscale
tile_get_y
tile_get_yscale
tile_layer_delete
tile_layer_delete_at
tile_layer_depth
tile_layer_find
tile_layer_hide
tile_layer_shift
tile_layer_show
tile_set_alpha
tile_set_background
tile_set_blend
tile_set_depth
tile_set_empty
tile_set_flip
tile_set_index
tile_set_mirror
tile_set_position
tile_set_region
tile_set_rotate
tile_set_scale
tile_set_visible
tilemap_clear
tilemap_get
tilemap_get_at_pixel
tilemap_get_cell_x_at_pixel
tilemap_get_cell_y_at_pixel
tilemap_get_frame
tilemap_get_global_mask
tilemap_get_height
tilemap_get_mask
tilemap_get_tile_height
tilemap_get_tile_width
tilemap_get_tileset
tilemap_get_width
tilemap_get_x
tilemap_get_y
tilemap_set
tilemap_set_at_pixel
tilemap_set_global_mask
tilemap_set_height
tilemap_set_mask
tilemap_set_width
tilemap_tileset
tilemap_x
tilemap_y
timeline_add
timeline_clear
timeline_delete
timeline_exists
timeline_get_name
timeline_max_moment
timeline_moment_add
timeline_moment_add_script
timeline_moment_clear
timeline_name
timeline_size
transition_define
transition_exists
typeof
url_get_domain
url_open
url_open_ext
url_open_full
uwp_check_privilege
uwp_is_constrained
uwp_is_suspending
uwp_license_trial_time_remaining
uwp_license_trial_user
uwp_license_trial_version
uwp_show_help
uwp_suspend
uwp_was_terminated
variable_global_exists
variable_global_get
variable_global_set
variable_instance_exists
variable_instance_get
variable_instance_get_names
variable_instance_set
vertex_argb
vertex_begin
vertex_color
vertex_colour
vertex_create_buffer
vertex_create_buffer_ext
vertex_create_buffer_from_buffer
vertex_create_buffer_from_buffer_ext
vertex_delete_buffer
vertex_end
vertex_float1
vertex_float2
vertex_float3
vertex_float4
vertex_format_add_color
vertex_format_add_colour
vertex_format_add_custom
vertex_format_add_normal
vertex_format_add_position
vertex_format_add_position_3d
vertex_format_add_texcoord
vertex_format_add_textcoord
vertex_format_begin
vertex_format_delete
vertex_format_end
vertex_freeze
vertex_get_buffer_size
vertex_get_number
vertex_normal
vertex_position
vertex_position_3d
vertex_submit
vertex_texcoord
vertex_ubyte4
video_close
video_draw
video_open
video_set_volume
view_get_camera
view_get_hport
view_get_surface_id
view_get_visible
view_get_wport
view_get_xport
view_get_yport
view_set_camera
view_set_hport
view_set_surface_id
view_set_visible
view_set_wport
view_set_xport
view_set_yport
virtual_key_add
virtual_key_delete
virtual_key_hide
virtual_key_show
win8_appbar_add_element
win8_appbar_enable
win8_appbar_remove_element
win8_device_touchscreen_available
win8_license_initialize_sandbox
win8_license_trial_version
win8_livetile_badge_clear
win8_livetile_badge_notification
win8_livetile_notification_begin
win8_livetile_notification_end
win8_livetile_notification_expiry
win8_livetile_notification_image_add
win8_livetile_notification_secondary_begin
win8_livetile_notification_tag
win8_livetile_notification_text_add
win8_livetile_queue_enable
win8_livetile_tile_clear
win8_livetile_tile_notification
win8_search_add_suggestions
win8_search_disable
win8_search_enable
win8_secondarytile_badge_notification
win8_secondarytile_delete
win8_secondarytile_pin
win8_settingscharm_add_entry
win8_settingscharm_add_html_entry
win8_settingscharm_add_xaml_entry
win8_settingscharm_get_xaml_property
win8_settingscharm_remove_entry
win8_settingscharm_set_xaml_property
win8_share_file
win8_share_image
win8_share_screenshot
win8_share_text
win8_share_url
window_center
window_default
window_device
window_get_caption
window_get_color
window_get_colour
window_get_cursor
window_get_fullscreen
window_get_height
window_get_showborder
window_get_showicons
window_get_sizeable
window_get_stayontop
window_get_visible
window_get_visible_rects
window_get_width
window_get_x
window_get_y
window_handle
window_has_focus
window_mouse_get_x
window_mouse_get_y
window_mouse_set
window_set_caption
window_set_color
window_set_colour
window_set_cursor
window_set_fullscreen
window_set_max_height
window_set_max_width
window_set_min_height
window_set_min_width
window_set_position
window_set_rectangle
window_set_showborder
window_set_showicons
window_set_size
window_set_sizeable
window_set_stayontop
window_set_visible
window_view_mouse_get_x
window_view_mouse_get_y
window_view_mouse_set
window_views_mouse_get_x
window_views_mouse_get_y
window_views_mouse_set
winphone_license_trial_version
winphone_tile_back_content
winphone_tile_back_content_wide
winphone_tile_back_image
winphone_tile_back_image_wide
winphone_tile_back_title
winphone_tile_background_color
winphone_tile_background_colour
winphone_tile_count
winphone_tile_cycle_images
winphone_tile_front_image
winphone_tile_front_image_small
winphone_tile_front_image_wide
winphone_tile_icon_image
winphone_tile_small_background_image
winphone_tile_small_icon_image
winphone_tile_title
winphone_tile_wide_content
xboxlive_achievements_set_progress
xboxlive_agegroup_for_user
xboxlive_appdisplayname_for_user
xboxlive_chat_add_user_to_channel
xboxlive_chat_remove_user_from_channel
xboxlive_chat_set_muted
xboxlive_fire_event
xboxlive_gamedisplayname_for_user
xboxlive_gamerscore_for_user
xboxlive_gamertag_for_user
xboxlive_generate_player_session_id
xboxlive_get_activating_user
xboxlive_get_file_error
xboxlive_get_savedata_user
xboxlive_get_stats_for_user
xboxlive_get_user
xboxlive_get_user_count
xboxlive_matchmaking_create
xboxlive_matchmaking_find
xboxlive_matchmaking_join_invite
xboxlive_matchmaking_join_session
xboxlive_matchmaking_send_invites
xboxlive_matchmaking_session_get_users
xboxlive_matchmaking_session_leave
xboxlive_matchmaking_set_find_timeout
xboxlive_matchmaking_set_joinable_session
xboxlive_matchmaking_start
xboxlive_matchmaking_stop
xboxlive_pad_count_for_user
xboxlive_pad_for_user
xboxlive_read_player_leaderboard
xboxlive_reputation_for_user
xboxlive_set_rich_presence
xboxlive_set_savedata_user
xboxlive_set_service_configuration_id
xboxlive_show_account_picker
xboxlive_show_profile_card_for_user
xboxlive_sponsor_for_user
xboxlive_sprite_add_from_gamerpicture
xboxlive_stats_add_user
xboxlive_stats_delete_stat
xboxlive_stats_flush_user
xboxlive_stats_get_leaderboard
xboxlive_stats_get_social_leaderboard
xboxlive_stats_get_stat
xboxlive_stats_get_stat_names
xboxlive_stats_remove_user
xboxlive_stats_set_stat_int
xboxlive_stats_set_stat_real
xboxlive_stats_set_stat_string
xboxlive_stats_setup
xboxlive_user_for_pad
xboxlive_user_id_for_user
xboxlive_user_is_active
xboxlive_user_is_guest
xboxlive_user_is_remote
xboxlive_user_is_signed_in
xboxlive_user_is_signing_in
xboxone_achievements_set_progress
xboxone_agegroup_for_user
xboxone_appdisplayname_for_user
xboxone_chat_add_user_to_channel
xboxone_chat_remove_user_from_channel
xboxone_chat_set_muted
xboxone_check_privilege
xboxone_fire_event
xboxone_gamedisplayname_for_user
xboxone_gamerscore_for_user
xboxone_generate_player_session_id
xboxone_get_activating_user
xboxone_get_file_error
xboxone_get_savedata_user
xboxone_get_stats_for_user
xboxone_get_user
xboxone_get_user_count
xboxone_is_constrained
xboxone_is_suspending
xboxone_license_trial_time_remaining
xboxone_license_trial_user
xboxone_license_trial_version
xboxone_matchmaking_create
xboxone_matchmaking_find
xboxone_matchmaking_join_invite
xboxone_matchmaking_join_session
xboxone_matchmaking_send_invites
xboxone_matchmaking_session_get_users
xboxone_matchmaking_session_leave
xboxone_matchmaking_set_find_timeout
xboxone_matchmaking_set_joinable_session
xboxone_matchmaking_start
xboxone_matchmaking_stop
xboxone_package_check_license
xboxone_pad_count_for_user
xboxone_pad_for_user
xboxone_read_player_leaderboard
xboxone_reputation_for_user
xboxone_set_rich_presence
xboxone_set_savedata_user
xboxone_set_service_configuration_id
xboxone_show_account_picker
xboxone_show_help
xboxone_show_profile_card_for_user
xboxone_sponsor_for_user
xboxone_sprite_add_from_gamerpicture
xboxone_stats_add_user
xboxone_stats_delete_stat
xboxone_stats_flush_user
xboxone_stats_get_leaderboard
xboxone_stats_get_social_leaderboard
xboxone_stats_get_stat
xboxone_stats_get_stat_names
xboxone_stats_remove_user
xboxone_stats_set_stat_int
xboxone_stats_set_stat_real
xboxone_stats_set_stat_string
xboxone_stats_setup
xboxone_suspend
xboxone_user_for_pad
xboxone_user_id_for_user
xboxone_user_is_active
xboxone_user_is_guest
xboxone_user_is_remote
xboxone_user_is_signed_in
xboxone_was_terminated
YoYo_AchievementsAvailable
YoYo_AddVirtualKey
YoYo_CheckSecurity
YoYo_DeleteVirtualKey
YoYo_DisableAds
YoYo_EnableAds
YoYo_EnableAlphaBlend
YoYo_GetConfig
YoYo_GetCPUDetails
YoYo_GetDevice
YoYo_GetPlatform
YoYo_GetSessionKey
YoYo_GetTiltX
YoYo_GetTiltY
YoYo_GetTiltZ
YoYo_GetTimer
YoYo_HideVirtualKey
YoYo_IsKeypadOpen
YoYo_LeaveRating
YoYo_LoginAchievements
YoYo_LogoutAchievements
YoYo_MouseCheckButton
YoYo_MouseCheckButtonPressed
YoYo_MouseCheckButtonReleased
YoYo_MouseX
YoYo_MouseXRaw
YoYo_MouseY
YoYo_MouseYRaw
YoYo_OF_AcceptChallenge
YoYo_OF_AddAchievement
YoYo_OF_AddLeaderboard
YoYo_OF_IsOnline
YoYo_OF_SendChallenge
YoYo_OF_SendChallengeResult
YoYo_OF_SendInvite
YoYo_OF_SendSocial
YoYo_OF_SetURL
YoYo_OF_StartDashboard
YoYo_OpenURL
YoYo_OpenURL_ext
YoYo_OpenURL_full
YoYo_OSPauseEvent
YoYo_PostAchievement
YoYo_PostScore
YoYo_ShowVirtualKey
yyg_player_launch_args
yyg_player_restarted
yyg_player_run
zip_unzip
";

pub const CONSTANTS: &str = "\
all
audio_3d
audio_falloff_exponent_distance
audio_falloff_exponent_distance_clamped
audio_falloff_inverse_distance
audio_falloff_inverse_distance_clamped
audio_falloff_linear_distance
audio_falloff_linear_distance_clamped
audio_falloff_none
audio_mono
audio_new_system
audio_old_system
audio_stereo
bm_add
bm_dest_alpha
bm_dest_color
bm_dest_colour
bm_inv_dest_alpha
bm_inv_dest_color
bm_inv_dest_colour
bm_inv_src_alpha
bm_inv_src_color
bm_inv_src_colour
bm_max
bm_normal
bm_one
bm_src_alpha
bm_src_alpha_sat
bm_src_color
bm_src_colour
bm_subtract
bm_zero
buffer_bool
buffer_f16
buffer_f32
buffer_f64
buffer_fast
buffer_fixed
buffer_grow
buffer_network
buffer_s16
buffer_s32
buffer_s8
buffer_seek_end
buffer_seek_relative
buffer_seek_start
buffer_string
buffer_surface_copy
buffer_text
buffer_u16
buffer_u32
buffer_u64
buffer_u8
buffer_vbuffer
buffer_wrap
c_aqua
c_black
c_blue
c_dkgray
c_fuchsia
c_gray
c_green
c_lime
c_ltgray
c_maroon
c_navy
c_olive
c_orange
c_purple
c_red
c_silver
c_teal
c_white
c_yellow
cr_appstart
cr_arrow
cr_beam
cr_cross
cr_default
cr_drag
cr_handpoint
cr_help
cr_hourglass
cr_hsplit
cr_multidrag
cr_no
cr_nodrop
cr_none
cr_size_all
cr_size_nesw
cr_size_ns
cr_size_nwse
cr_size_we
cr_sqlwait
cr_uparrow
cr_vsplit
display_landscape
display_landscape_flipped
display_portrait
display_portrait_flipped
dll_cdecl
dll_stdcall
ef_cloud
ef_ellipse
ef_explosion
ef_firework
ef_flare
ef_rain
ef_ring
ef_smoke
ef_smokeup
ef_snow
ef_spark
ef_star
ev_alarm
ev_animation_end
ev_async
ev_audio_playback
ev_audio_recording
ev_boundary
ev_clean_up
ev_cleanup
ev_close_button
ev_cloud
ev_collision
ev_create
ev_destroy
ev_dialog
ev_draw
ev_end_of_path
ev_game_end
ev_game_start
ev_gesture
ev_gesture_double_tap
ev_gesture_drag_end
ev_gesture_drag_start
ev_gesture_dragging
ev_gesture_flick
ev_gesture_pinch_end
ev_gesture_pinch_in
ev_gesture_pinch_out
ev_gesture_pinch_start
ev_gesture_rotate_end
ev_gesture_rotate_start
ev_gesture_rotating
ev_gesture_tap
ev_global_gesture_double_tap
ev_global_gesture_drag_end
ev_global_gesture_drag_start
ev_global_gesture_dragging
ev_global_gesture_flick
ev_global_gesture_pinch_end
ev_global_gesture_pinch_in
ev_global_gesture_pinch_out
ev_global_gesture_pinch_start
ev_global_gesture_rotate_end
ev_global_gesture_rotate_start
ev_global_gesture_rotating
ev_global_gesture_tap
ev_global_left_button
ev_global_left_press
ev_global_left_release
ev_global_middle_button
ev_global_middle_press
ev_global_middle_release
ev_global_press
ev_global_release
ev_global_right_button
ev_global_right_press
ev_global_right_release
ev_gui
ev_iap
ev_joystick1_button1
ev_joystick1_button2
ev_joystick1_button3
ev_joystick1_button4
ev_joystick1_button5
ev_joystick1_button6
ev_joystick1_button7
ev_joystick1_button8
ev_joystick1_down
ev_joystick1_left
ev_joystick1_right
ev_joystick1_up
ev_joystick2_button1
ev_joystick2_button2
ev_joystick2_button3
ev_joystick2_button4
ev_joystick2_button5
ev_joystick2_button6
ev_joystick2_button7
ev_joystick2_button8
ev_joystick2_down
ev_joystick2_left
ev_joystick2_right
ev_joystick2_up
ev_keyboard
ev_keypress
ev_keyrelease
ev_left_button
ev_left_press
ev_left_release
ev_middle_button
ev_middle_press
ev_middle_release
ev_mouse
ev_mouse_enter
ev_mouse_leave
ev_mouse_wheel_down
ev_mouse_wheel_up
ev_networking
ev_no_button
ev_no_more_health
ev_no_more_lives
ev_other
ev_outside
ev_pre_create
ev_push_notification
ev_right_button
ev_right_press
ev_right_release
ev_room_end
ev_room_start
ev_save_load
ev_social
ev_steam
ev_step
ev_step_begin
ev_step_end
ev_step_normal
ev_system_event
ev_trigger
ev_user0
ev_user1
ev_user10
ev_user11
ev_user12
ev_user13
ev_user14
ev_user15
ev_user2
ev_user3
ev_user4
ev_user5
ev_user6
ev_user7
ev_user8
ev_user9
fa_archive
fa_bottom
fa_center
fa_directory
fa_hidden
fa_left
fa_middle
fa_readonly
fa_right
fa_sysfile
fa_top
fa_volumeid
false
global
gp_axislh
gp_axislv
gp_axisrh
gp_axisrv
gp_face1
gp_face2
gp_face3
gp_face4
gp_padd
gp_padl
gp_padr
gp_padu
gp_select
gp_shoulderl
gp_shoulderlb
gp_shoulderr
gp_shoulderrb
gp_start
gp_stickl
gp_stickr
lb_disp_none
lb_disp_numeric
lb_disp_time_ms
lb_disp_time_sec
lb_sort_ascending
lb_sort_descending
lb_sort_none
local
matrix_projection
matrix_view
matrix_world
mb_any
mb_left
mb_middle
mb_none
mb_right
mip_markedonly
mip_off
mip_on
noone
os_3ds
os_android
os_bb10
os_ios
os_linux
os_macosx
os_ps3
os_ps4
os_psp
os_psvita
os_symbian
os_tizen
os_tvos
os_unknown
os_uwp
os_wiiu
os_win32
os_win8native
os_windows
os_winphone
os_xbox360
os_xboxone
other
ov_achievements
ov_community
ov_friends
ov_gamegroup
ov_players
ov_settings
path_action_continue
path_action_restart
path_action_stop
phy_debug_render_aabb
phy_debug_render_collision_pairs
phy_debug_render_coms
phy_debug_render_core_shapes
phy_debug_render_joints
phy_debug_render_obb
phy_debug_render_shapes
phy_joint_anchor_1_x
phy_joint_anchor_1_y
phy_joint_anchor_2_x
phy_joint_anchor_2_y
phy_joint_angle
phy_joint_damping_ratio
phy_joint_frequency
phy_joint_length_1
phy_joint_length_2
phy_joint_max_motor_force
phy_joint_max_motor_torque
phy_joint_motor_force
phy_joint_motor_speed
phy_joint_motor_torque
phy_joint_reaction_force_x
phy_joint_reaction_force_y
phy_joint_reaction_torque
phy_joint_speed
phy_joint_translation
pi
pr_linelist
pr_linestrip
pr_pointlist
pr_trianglefan
pr_trianglelist
pr_trianglestrip
ps_change_all
ps_change_motion
ps_change_shape
ps_deflect_horizontal
ps_deflect_vertical
ps_distr_gaussian
ps_distr_invgaussian
ps_distr_linear
ps_force_constant
ps_force_linear
ps_force_quadratic
ps_shape_diamond
ps_shape_ellipse
ps_shape_line
ps_shape_rectangle
pt_shape_circle
pt_shape_cloud
pt_shape_disk
pt_shape_explosion
pt_shape_flare
pt_shape_line
pt_shape_pixel
pt_shape_ring
pt_shape_smoke
pt_shape_snow
pt_shape_spark
pt_shape_sphere
pt_shape_square
pt_shape_star
self
tf_anisotropic
tf_linear
tf_point
timezone_local
timezone_utc
true
ty_real
ty_string
ugc_filetype_community
ugc_filetype_microtrans
ugc_list_Favorited
ugc_list_Followed
ugc_list_Published
ugc_list_Subscribed
ugc_list_UsedOrPlayed
ugc_list_VotedDown
ugc_list_VotedOn
ugc_list_VotedUp
ugc_list_WillVoteLater
ugc_match_AllGuides
ugc_match_Artwork
ugc_match_Collections
ugc_match_ControllerBindings
ugc_match_IntegratedGuides
ugc_match_Items
ugc_match_Items_Mtx
ugc_match_Items_ReadyToUse
ugc_match_Screenshots
ugc_match_UsableInGame
ugc_match_Videos
ugc_match_WebGuides
ugc_query_AcceptedForGameRankedByAcceptanceDate
ugc_query_CreatedByFollowedUsersRankedByPublicationDate
ugc_query_CreatedByFriendsRankedByPublicationDate
ugc_query_FavoritedByFriendsRankedByPublicationDate
ugc_query_NotYetRated
ugc_query_RankedByNumTimesReported
ugc_query_RankedByPublicationDate
ugc_query_RankedByTextSearch
ugc_query_RankedByTotalVotesAsc
ugc_query_RankedByTrend
ugc_query_RankedByVote
ugc_query_RankedByVotesUp
ugc_result_success
ugc_sortorder_CreationOrderAsc
ugc_sortorder_CreationOrderDesc
ugc_sortorder_ForModeration
ugc_sortorder_LastUpdatedDesc
ugc_sortorder_SubscriptionDateDesc
ugc_sortorder_TitleAsc
ugc_sortorder_VoteScoreDesc
ugc_visibility_friends_only
ugc_visibility_private
ugc_visibility_public
vk_add
vk_alt
vk_anykey
vk_backspace
vk_control
vk_decimal
vk_delete
vk_divide
vk_down
vk_end
vk_enter
vk_escape
vk_f1
vk_f10
vk_f11
vk_f12
vk_f2
vk_f3
vk_f4
vk_f5
vk_f6
vk_f7
vk_f8
vk_f9
vk_home
vk_insert
vk_lalt
vk_lcontrol
vk_left
vk_lshift
vk_multiply
vk_nokey
vk_numpad0
vk_numpad1
vk_numpad2
vk_numpad3
vk_numpad4
vk_numpad5
vk_numpad6
vk_numpad7
vk_numpad8
vk_numpad9
vk_pagedown
vk_pageup
vk_pause
vk_printscreen
vk_ralt
vk_rcontrol
vk_return
vk_right
vk_rshift
vk_shift
vk_space
vk_subtract
vk_tab
vk_up
";

/// Numeric values registered by the Windows GMS 1.4.9999 runner and compiler.
/// Compiler-only aliases used by project source are included as well.
pub fn constant_value(name: &str) -> Option<f64> {
    let value = match name {
        "all" => -3.0,
        "audio_3d" => 2.0,
        "audio_falloff_exponent_distance" => 5.0,
        "audio_falloff_exponent_distance_clamped" => 6.0,
        "audio_falloff_inverse_distance" => 1.0,
        "audio_falloff_inverse_distance_clamped" => 2.0,
        "audio_falloff_linear_distance" => 3.0,
        "audio_falloff_linear_distance_clamped" => 4.0,
        "audio_falloff_none" => 0.0,
        "audio_mono" => 0.0,
        "audio_new_system" => 1.0,
        "audio_old_system" => 0.0,
        "audio_stereo" => 1.0,
        "bm_add" => 1.0,
        "bm_dest_alpha" => 7.0,
        "bm_dest_color" => 9.0,
        "bm_dest_colour" => 9.0,
        "bm_inv_dest_alpha" => 8.0,
        "bm_inv_dest_color" => 10.0,
        "bm_inv_dest_colour" => 10.0,
        "bm_inv_src_alpha" => 6.0,
        "bm_inv_src_color" => 4.0,
        "bm_inv_src_colour" => 4.0,
        "bm_max" => 2.0,
        "bm_normal" => 0.0,
        "bm_one" => 2.0,
        "bm_src_alpha" => 5.0,
        "bm_src_alpha_sat" => 11.0,
        "bm_src_color" => 3.0,
        "bm_src_colour" => 3.0,
        "bm_subtract" => 3.0,
        "bm_zero" => 1.0,
        "buffer_bool" => 10.0,
        "buffer_f16" => 7.0,
        "buffer_f32" => 8.0,
        "buffer_f64" => 9.0,
        "buffer_fast" => 3.0,
        "buffer_fixed" => 0.0,
        "buffer_grow" => 1.0,
        "buffer_network" => 5.0,
        "buffer_s16" => 4.0,
        "buffer_s32" => 6.0,
        "buffer_s8" => 2.0,
        "buffer_seek_end" => 2.0,
        "buffer_seek_relative" => 1.0,
        "buffer_seek_start" => 0.0,
        "buffer_string" => 11.0,
        "buffer_surface_copy" => 0.0,
        "buffer_text" => 13.0,
        "buffer_u16" => 3.0,
        "buffer_u32" => 5.0,
        "buffer_u64" => 12.0,
        "buffer_u8" => 1.0,
        "buffer_vbuffer" => 4.0,
        "buffer_wrap" => 2.0,
        "c_aqua" => 16776960.0,
        "c_black" => 0.0,
        "c_blue" => 16711680.0,
        "c_dkgray" => 4210752.0,
        "c_fuchsia" => 16711935.0,
        "c_gray" => 8421504.0,
        "c_green" => 32768.0,
        "c_lime" => 65280.0,
        "c_ltgray" => 12632256.0,
        "c_maroon" => 128.0,
        "c_navy" => 8388608.0,
        "c_olive" => 32896.0,
        "c_orange" => 4235519.0,
        "c_purple" => 8388736.0,
        "c_red" => 255.0,
        "c_silver" => 12632256.0,
        "c_teal" => 8421376.0,
        "c_white" => 16777215.0,
        "c_yellow" => 65535.0,
        "cr_appstart" => -19.0,
        "cr_arrow" => -2.0,
        "cr_beam" => -4.0,
        "cr_cross" => -3.0,
        "cr_default" => 0.0,
        "cr_drag" => -12.0,
        "cr_handpoint" => -21.0,
        "cr_help" => -20.0,
        "cr_hourglass" => -11.0,
        "cr_hsplit" => -14.0,
        "cr_multidrag" => -16.0,
        "cr_no" => -18.0,
        "cr_nodrop" => -13.0,
        "cr_none" => -1.0,
        "cr_size_all" => -22.0,
        "cr_size_nesw" => -6.0,
        "cr_size_ns" => -7.0,
        "cr_size_nwse" => -8.0,
        "cr_size_we" => -9.0,
        "cr_sqlwait" => -17.0,
        "cr_uparrow" => -10.0,
        "cr_vsplit" => -15.0,
        "display_landscape" => 0.0,
        "display_landscape_flipped" => 2.0,
        "display_portrait" => 1.0,
        "display_portrait_flipped" => 3.0,
        "dll_cdecl" => 0.0,
        "dll_stdcall" => 1.0,
        "ef_cloud" => 9.0,
        "ef_ellipse" => 2.0,
        "ef_explosion" => 0.0,
        "ef_firework" => 3.0,
        "ef_flare" => 8.0,
        "ef_rain" => 10.0,
        "ef_ring" => 1.0,
        "ef_smoke" => 4.0,
        "ef_smokeup" => 5.0,
        "ef_snow" => 11.0,
        "ef_spark" => 7.0,
        "ef_star" => 6.0,
        "ev_alarm" => 2.0,
        "ev_animation_end" => 7.0,
        "ev_async" => 62.0,
        "ev_audio_playback" => 74.0,
        "ev_audio_recording" => 73.0,
        "ev_boundary" => 1.0,
        "ev_clean_up" => 12.0,
        "ev_cleanup" => 11.0,
        "ev_close_button" => 30.0,
        "ev_cloud" => 67.0,
        "ev_collision" => 4.0,
        "ev_create" => 0.0,
        "ev_destroy" => 1.0,
        "ev_dialog" => 63.0,
        "ev_draw" => 8.0,
        "ev_end_of_path" => 8.0,
        "ev_game_end" => 3.0,
        "ev_game_start" => 2.0,
        "ev_gesture" => 13.0,
        "ev_gesture_double_tap" => 1.0,
        "ev_gesture_drag_end" => 4.0,
        "ev_gesture_drag_start" => 2.0,
        "ev_gesture_dragging" => 3.0,
        "ev_gesture_flick" => 5.0,
        "ev_gesture_pinch_end" => 9.0,
        "ev_gesture_pinch_in" => 7.0,
        "ev_gesture_pinch_out" => 8.0,
        "ev_gesture_pinch_start" => 6.0,
        "ev_gesture_rotate_end" => 12.0,
        "ev_gesture_rotate_start" => 10.0,
        "ev_gesture_rotating" => 11.0,
        "ev_gesture_tap" => 0.0,
        "ev_global_gesture_double_tap" => 65.0,
        "ev_global_gesture_drag_end" => 68.0,
        "ev_global_gesture_drag_start" => 66.0,
        "ev_global_gesture_dragging" => 67.0,
        "ev_global_gesture_flick" => 69.0,
        "ev_global_gesture_pinch_end" => 73.0,
        "ev_global_gesture_pinch_in" => 71.0,
        "ev_global_gesture_pinch_out" => 72.0,
        "ev_global_gesture_pinch_start" => 70.0,
        "ev_global_gesture_rotate_end" => 76.0,
        "ev_global_gesture_rotate_start" => 74.0,
        "ev_global_gesture_rotating" => 75.0,
        "ev_global_gesture_tap" => 64.0,
        "ev_global_left_button" => 50.0,
        "ev_global_left_press" => 53.0,
        "ev_global_left_release" => 56.0,
        "ev_global_middle_button" => 52.0,
        "ev_global_middle_press" => 55.0,
        "ev_global_middle_release" => 58.0,
        "ev_global_press" => 12.0,
        "ev_global_release" => 13.0,
        "ev_global_right_button" => 51.0,
        "ev_global_right_press" => 54.0,
        "ev_global_right_release" => 57.0,
        "ev_gui" => 64.0,
        "ev_iap" => 66.0,
        "ev_joystick1_button1" => 21.0,
        "ev_joystick1_button2" => 22.0,
        "ev_joystick1_button3" => 23.0,
        "ev_joystick1_button4" => 24.0,
        "ev_joystick1_button5" => 25.0,
        "ev_joystick1_button6" => 26.0,
        "ev_joystick1_button7" => 27.0,
        "ev_joystick1_button8" => 28.0,
        "ev_joystick1_down" => 19.0,
        "ev_joystick1_left" => 16.0,
        "ev_joystick1_right" => 17.0,
        "ev_joystick1_up" => 18.0,
        "ev_joystick2_button1" => 36.0,
        "ev_joystick2_button2" => 37.0,
        "ev_joystick2_button3" => 38.0,
        "ev_joystick2_button4" => 39.0,
        "ev_joystick2_button5" => 40.0,
        "ev_joystick2_button6" => 41.0,
        "ev_joystick2_button7" => 42.0,
        "ev_joystick2_button8" => 43.0,
        "ev_joystick2_down" => 34.0,
        "ev_joystick2_left" => 31.0,
        "ev_joystick2_right" => 32.0,
        "ev_joystick2_up" => 33.0,
        "ev_keyboard" => 5.0,
        "ev_keypress" => 9.0,
        "ev_keyrelease" => 10.0,
        "ev_left_button" => 0.0,
        "ev_left_press" => 4.0,
        "ev_left_release" => 7.0,
        "ev_middle_button" => 2.0,
        "ev_middle_press" => 6.0,
        "ev_middle_release" => 9.0,
        "ev_mouse" => 6.0,
        "ev_mouse_enter" => 10.0,
        "ev_mouse_leave" => 11.0,
        "ev_mouse_wheel_down" => 61.0,
        "ev_mouse_wheel_up" => 60.0,
        "ev_networking" => 68.0,
        "ev_no_button" => 3.0,
        "ev_no_more_health" => 9.0,
        "ev_no_more_lives" => 6.0,
        "ev_other" => 7.0,
        "ev_outside" => 0.0,
        "ev_pre_create" => 14.0,
        "ev_push_notification" => 71.0,
        "ev_right_button" => 1.0,
        "ev_right_press" => 5.0,
        "ev_right_release" => 8.0,
        "ev_room_end" => 5.0,
        "ev_room_start" => 4.0,
        "ev_save_load" => 72.0,
        "ev_social" => 70.0,
        "ev_steam" => 69.0,
        "ev_step" => 3.0,
        "ev_step_begin" => 1.0,
        "ev_step_end" => 2.0,
        "ev_step_normal" => 0.0,
        "ev_system_event" => 75.0,
        "ev_trigger" => 11.0,
        "ev_user0" => 10.0,
        "ev_user1" => 11.0,
        "ev_user10" => 20.0,
        "ev_user11" => 21.0,
        "ev_user12" => 22.0,
        "ev_user13" => 23.0,
        "ev_user14" => 24.0,
        "ev_user15" => 25.0,
        "ev_user2" => 12.0,
        "ev_user3" => 13.0,
        "ev_user4" => 14.0,
        "ev_user5" => 15.0,
        "ev_user6" => 16.0,
        "ev_user7" => 17.0,
        "ev_user8" => 18.0,
        "ev_user9" => 19.0,
        "fa_archive" => 32.0,
        "fa_bottom" => 2.0,
        "fa_center" => 1.0,
        "fa_directory" => 16.0,
        "fa_hidden" => 2.0,
        "fa_left" => 0.0,
        "fa_middle" => 1.0,
        "fa_readonly" => 1.0,
        "fa_right" => 2.0,
        "fa_sysfile" => 4.0,
        "fa_top" => 0.0,
        "fa_volumeid" => 8.0,
        "false" => 0.0,
        "global" => -5.0,
        "gp_axislh" => 32785.0,
        "gp_axislv" => 32786.0,
        "gp_axisrh" => 32787.0,
        "gp_axisrv" => 32788.0,
        "gp_face1" => 32769.0,
        "gp_face2" => 32770.0,
        "gp_face3" => 32771.0,
        "gp_face4" => 32772.0,
        "gp_padd" => 32782.0,
        "gp_padl" => 32783.0,
        "gp_padr" => 32784.0,
        "gp_padu" => 32781.0,
        "gp_select" => 32777.0,
        "gp_shoulderl" => 32773.0,
        "gp_shoulderlb" => 32775.0,
        "gp_shoulderr" => 32774.0,
        "gp_shoulderrb" => 32776.0,
        "gp_start" => 32778.0,
        "gp_stickl" => 32779.0,
        "gp_stickr" => 32780.0,
        "lb_disp_none" => 0.0,
        "lb_disp_numeric" => 1.0,
        "lb_disp_time_ms" => 3.0,
        "lb_disp_time_sec" => 2.0,
        "lb_sort_ascending" => 1.0,
        "lb_sort_descending" => 2.0,
        "lb_sort_none" => 0.0,
        "local" => -7.0,
        "matrix_projection" => 1.0,
        "matrix_view" => 0.0,
        "matrix_world" => 2.0,
        "mb_any" => -1.0,
        "mb_left" => 1.0,
        "mb_middle" => 3.0,
        "mb_none" => 0.0,
        "mb_right" => 2.0,
        "mip_markedonly" => 2.0,
        "mip_off" => 0.0,
        "mip_on" => 1.0,
        "noone" => -4.0,
        "os_3ds" => 11.0,
        "os_android" => 4.0,
        "os_bb10" => 13.0,
        "os_ios" => 3.0,
        "os_linux" => 6.0,
        "os_macosx" => 1.0,
        "os_ps3" => 16.0,
        "os_ps4" => 14.0,
        "os_psp" => 2.0,
        "os_psvita" => 12.0,
        "os_symbian" => 5.0,
        "os_tizen" => 8.0,
        "os_tvos" => 20.0,
        "os_unknown" => -1.0,
        "os_uwp" => 18.0,
        "os_wiiu" => 10.0,
        "os_win32" => 0.0,
        "os_win8native" => 9.0,
        "os_windows" => 0.0,
        "os_winphone" => 7.0,
        "os_xbox360" => 17.0,
        "os_xboxone" => 15.0,
        "other" => -2.0,
        "ov_achievements" => 5.0,
        "ov_community" => 1.0,
        "ov_friends" => 0.0,
        "ov_gamegroup" => 4.0,
        "ov_players" => 2.0,
        "ov_settings" => 3.0,
        "path_action_continue" => 2.0,
        "path_action_restart" => 1.0,
        "path_action_stop" => 0.0,
        "phy_debug_render_aabb" => 8.0,
        "phy_debug_render_collision_pairs" => 64.0,
        "phy_debug_render_coms" => 4.0,
        "phy_debug_render_core_shapes" => 32.0,
        "phy_debug_render_joints" => 2.0,
        "phy_debug_render_obb" => 16.0,
        "phy_debug_render_shapes" => 1.0,
        "phy_joint_anchor_1_x" => 0.0,
        "phy_joint_anchor_1_y" => 1.0,
        "phy_joint_anchor_2_x" => 2.0,
        "phy_joint_anchor_2_y" => 3.0,
        "phy_joint_angle" => 8.0,
        "phy_joint_damping_ratio" => 17.0,
        "phy_joint_frequency" => 18.0,
        "phy_joint_length_1" => 15.0,
        "phy_joint_length_2" => 16.0,
        "phy_joint_max_motor_force" => 14.0,
        "phy_joint_max_motor_torque" => 10.0,
        "phy_joint_motor_force" => 13.0,
        "phy_joint_motor_speed" => 7.0,
        "phy_joint_motor_torque" => 9.0,
        "phy_joint_reaction_force_x" => 4.0,
        "phy_joint_reaction_force_y" => 5.0,
        "phy_joint_reaction_torque" => 6.0,
        "phy_joint_speed" => 12.0,
        "phy_joint_translation" => 11.0,
        "pi" => std::f64::consts::PI,
        "pr_linelist" => 2.0,
        "pr_linestrip" => 3.0,
        "pr_pointlist" => 1.0,
        "pr_trianglefan" => 6.0,
        "pr_trianglelist" => 4.0,
        "pr_trianglestrip" => 5.0,
        "ps_change_all" => 0.0,
        "ps_change_motion" => 2.0,
        "ps_change_shape" => 1.0,
        "ps_deflect_horizontal" => 1.0,
        "ps_deflect_vertical" => 0.0,
        "ps_distr_gaussian" => 1.0,
        "ps_distr_invgaussian" => 2.0,
        "ps_distr_linear" => 0.0,
        "ps_force_constant" => 0.0,
        "ps_force_linear" => 1.0,
        "ps_force_quadratic" => 2.0,
        "ps_shape_diamond" => 2.0,
        "ps_shape_ellipse" => 1.0,
        "ps_shape_line" => 3.0,
        "ps_shape_rectangle" => 0.0,
        "pt_shape_circle" => 5.0,
        "pt_shape_cloud" => 11.0,
        "pt_shape_disk" => 1.0,
        "pt_shape_explosion" => 10.0,
        "pt_shape_flare" => 8.0,
        "pt_shape_line" => 3.0,
        "pt_shape_pixel" => 0.0,
        "pt_shape_ring" => 6.0,
        "pt_shape_smoke" => 12.0,
        "pt_shape_snow" => 13.0,
        "pt_shape_spark" => 9.0,
        "pt_shape_sphere" => 7.0,
        "pt_shape_square" => 2.0,
        "pt_shape_star" => 4.0,
        "self" => -1.0,
        "tf_anisotropic" => 2.0,
        "tf_linear" => 1.0,
        "tf_point" => 0.0,
        "timezone_local" => 0.0,
        "timezone_utc" => 1.0,
        "true" => 1.0,
        "ty_real" => 0.0,
        "ty_string" => 1.0,
        "ugc_filetype_community" => 0.0,
        "ugc_filetype_microtrans" => 1.0,
        "ugc_list_Favorited" => 5.0,
        "ugc_list_Followed" => 8.0,
        "ugc_list_Published" => 0.0,
        "ugc_list_Subscribed" => 6.0,
        "ugc_list_UsedOrPlayed" => 7.0,
        "ugc_list_VotedDown" => 3.0,
        "ugc_list_VotedOn" => 1.0,
        "ugc_list_VotedUp" => 2.0,
        "ugc_list_WillVoteLater" => 4.0,
        "ugc_match_AllGuides" => 7.0,
        "ugc_match_Artwork" => 4.0,
        "ugc_match_Collections" => 3.0,
        "ugc_match_ControllerBindings" => 11.0,
        "ugc_match_IntegratedGuides" => 9.0,
        "ugc_match_Items" => 0.0,
        "ugc_match_Items_Mtx" => 1.0,
        "ugc_match_Items_ReadyToUse" => 2.0,
        "ugc_match_Screenshots" => 6.0,
        "ugc_match_UsableInGame" => 10.0,
        "ugc_match_Videos" => 5.0,
        "ugc_match_WebGuides" => 8.0,
        "ugc_query_AcceptedForGameRankedByAcceptanceDate" => 2.0,
        "ugc_query_CreatedByFollowedUsersRankedByPublicationDate" => 7.0,
        "ugc_query_CreatedByFriendsRankedByPublicationDate" => 5.0,
        "ugc_query_FavoritedByFriendsRankedByPublicationDate" => 4.0,
        "ugc_query_NotYetRated" => 8.0,
        "ugc_query_RankedByNumTimesReported" => 6.0,
        "ugc_query_RankedByPublicationDate" => 1.0,
        "ugc_query_RankedByTextSearch" => 11.0,
        "ugc_query_RankedByTotalVotesAsc" => 9.0,
        "ugc_query_RankedByTrend" => 3.0,
        "ugc_query_RankedByVote" => 0.0,
        "ugc_query_RankedByVotesUp" => 10.0,
        "ugc_result_success" => 1.0,
        "ugc_sortorder_CreationOrderAsc" => 1.0,
        "ugc_sortorder_CreationOrderDesc" => 0.0,
        "ugc_sortorder_ForModeration" => 6.0,
        "ugc_sortorder_LastUpdatedDesc" => 3.0,
        "ugc_sortorder_SubscriptionDateDesc" => 4.0,
        "ugc_sortorder_TitleAsc" => 2.0,
        "ugc_sortorder_VoteScoreDesc" => 5.0,
        "ugc_visibility_friends_only" => 1.0,
        "ugc_visibility_private" => 2.0,
        "ugc_visibility_public" => 0.0,
        "vk_add" => 107.0,
        "vk_alt" => 18.0,
        "vk_anykey" => 1.0,
        "vk_backspace" => 8.0,
        "vk_control" => 17.0,
        "vk_decimal" => 110.0,
        "vk_delete" => 46.0,
        "vk_divide" => 111.0,
        "vk_down" => 40.0,
        "vk_end" => 35.0,
        "vk_enter" => 13.0,
        "vk_escape" => 27.0,
        "vk_f1" => 112.0,
        "vk_f10" => 121.0,
        "vk_f11" => 122.0,
        "vk_f12" => 123.0,
        "vk_f2" => 113.0,
        "vk_f3" => 114.0,
        "vk_f4" => 115.0,
        "vk_f5" => 116.0,
        "vk_f6" => 117.0,
        "vk_f7" => 118.0,
        "vk_f8" => 119.0,
        "vk_f9" => 120.0,
        "vk_home" => 36.0,
        "vk_insert" => 45.0,
        "vk_lalt" => 164.0,
        "vk_lcontrol" => 162.0,
        "vk_left" => 37.0,
        "vk_lshift" => 160.0,
        "vk_multiply" => 106.0,
        "vk_nokey" => 0.0,
        "vk_numpad0" => 96.0,
        "vk_numpad1" => 97.0,
        "vk_numpad2" => 98.0,
        "vk_numpad3" => 99.0,
        "vk_numpad4" => 100.0,
        "vk_numpad5" => 101.0,
        "vk_numpad6" => 102.0,
        "vk_numpad7" => 103.0,
        "vk_numpad8" => 104.0,
        "vk_numpad9" => 105.0,
        "vk_pagedown" => 34.0,
        "vk_pageup" => 33.0,
        "vk_pause" => 19.0,
        "vk_printscreen" => 44.0,
        "vk_ralt" => 165.0,
        "vk_rcontrol" => 163.0,
        "vk_return" => 13.0,
        "vk_right" => 39.0,
        "vk_rshift" => 161.0,
        "vk_shift" => 16.0,
        "vk_space" => 32.0,
        "vk_subtract" => 109.0,
        "vk_tab" => 9.0,
        "vk_up" => 38.0,
        _ => return None,
    };
    Some(value)
}

pub const VARIABLES: &str = "\
alarm
application_surface
argument
argument_count
argument_relative
argument0
argument1
argument10
argument11
argument12
argument13
argument14
argument15
argument2
argument3
argument4
argument5
argument6
argument7
argument8
argument9
async_load
background_alpha
background_blend
background_color
background_colour
background_foreground
background_height
background_hspeed
background_htiled
background_index
background_showcolor
background_showcolour
background_visible
background_vspeed
background_vtiled
background_width
background_x
background_xscale
background_y
background_yscale
bbox_bottom
bbox_left
bbox_right
bbox_top
browser_height
browser_width
caption_health
caption_lives
caption_score
current_day
current_hour
current_minute
current_month
current_second
current_time
current_weekday
current_year
cursor_sprite
debug_mode
delta_time
depth
direction
display_aa
error_last
error_occurred
event_action
event_data
event_number
event_object
event_type
font_texture_page_size
fps
fps_real
friction
game_display_name
game_guid
game_id
game_project_name
game_save_id
gamemaker_pro
gamemaker_registered
gravity
gravity_direction
health
hspeed
iap_data
id
image_alpha
image_angle
image_blend
image_index
image_number
image_single
image_speed
image_xscale
image_yscale
instance_count
instance_id
keyboard_key
keyboard_lastchar
keyboard_lastkey
keyboard_string
layer
lives
mask_index
mouse_button
mouse_lastbutton
mouse_x
mouse_y
object_index
os_browser
os_device
os_type
os_version
path_endaction
path_index
path_orientation
path_position
path_positionprevious
path_scale
path_speed
persistent
phy_active
phy_angular_damping
phy_angular_velocity
phy_bullet
phy_col_normal_x
phy_col_normal_y
phy_collision_points
phy_collision_x
phy_collision_y
phy_com_x
phy_com_y
phy_dynamic
phy_fixed_rotation
phy_inertia
phy_kinematic
phy_linear_damping
phy_linear_velocity_x
phy_linear_velocity_y
phy_mass
phy_position_x
phy_position_xprevious
phy_position_y
phy_position_yprevious
phy_rotation
phy_sleeping
phy_speed
phy_speed_x
phy_speed_y
pointer_invalid
pointer_null
program_directory
room
room_caption
room_first
room_height
room_last
room_persistent
room_speed
room_width
score
secure_mode
show_health
show_lives
show_score
solid
speed
sprite_height
sprite_index
sprite_width
sprite_xoffset
sprite_yoffset
temp_directory
timeline_index
timeline_loop
timeline_position
timeline_running
timeline_speed
transition_kind
transition_steps
undefined
view_angle
view_camera
view_current
view_enabled
view_hborder
view_hport
view_hspeed
view_hview
view_object
view_surface_id
view_vborder
view_visible
view_vspeed
view_wport
view_wview
view_xport
view_xview
view_yport
view_yview
visible
vspeed
webgl_enabled
working_directory
x
xprevious
xstart
y
yprevious
ystart
";

pub fn is_variable(name: &str) -> bool {
    VARIABLES.lines().any(|candidate| candidate == name)
}

/// Legacy built-in arrays for which the 1.4 parser inserts index zero when
/// source code omits brackets.
pub fn is_array_variable(name: &str) -> bool {
    matches!(
        name,
        "background_alpha"
            | "background_blend"
            | "background_foreground"
            | "background_height"
            | "background_hspeed"
            | "background_htiled"
            | "background_index"
            | "background_visible"
            | "background_vspeed"
            | "background_vtiled"
            | "background_width"
            | "background_x"
            | "background_xscale"
            | "background_y"
            | "background_yscale"
            | "phy_col_normal_x"
            | "phy_col_normal_y"
            | "phy_collision_x"
            | "phy_collision_y"
            | "view_angle"
            | "view_camera"
            | "view_hborder"
            | "view_hport"
            | "view_hspeed"
            | "view_hview"
            | "view_object"
            | "view_surface_id"
            | "view_vborder"
            | "view_vspeed"
            | "view_wport"
            | "view_wview"
            | "view_xport"
            | "view_xview"
            | "view_yport"
            | "view_yview"
    )
}

/// Per-instance built-ins are encoded with the regular PUSH opcode. The
/// specialized PUSH_BUILTIN form is reserved for runner-global built-ins.
pub fn is_instance_variable(name: &str) -> bool {
    matches!(
        name,
        "alarm"
            | "bbox_bottom"
            | "bbox_left"
            | "bbox_right"
            | "bbox_top"
            | "depth"
            | "direction"
            | "friction"
            | "gravity"
            | "gravity_direction"
            | "hspeed"
            | "id"
            | "image_alpha"
            | "image_angle"
            | "image_blend"
            | "image_index"
            | "image_number"
            | "image_single"
            | "image_speed"
            | "image_xscale"
            | "image_yscale"
            | "layer"
            | "mask_index"
            | "object_index"
            | "path_endaction"
            | "path_index"
            | "path_orientation"
            | "path_position"
            | "path_positionprevious"
            | "path_scale"
            | "path_speed"
            | "persistent"
            | "phy_active"
            | "phy_angular_damping"
            | "phy_angular_velocity"
            | "phy_bullet"
            | "phy_col_normal_x"
            | "phy_col_normal_y"
            | "phy_collision_points"
            | "phy_collision_x"
            | "phy_collision_y"
            | "phy_com_x"
            | "phy_com_y"
            | "phy_dynamic"
            | "phy_fixed_rotation"
            | "phy_inertia"
            | "phy_kinematic"
            | "phy_linear_damping"
            | "phy_linear_velocity_x"
            | "phy_linear_velocity_y"
            | "phy_mass"
            | "phy_position_x"
            | "phy_position_xprevious"
            | "phy_position_y"
            | "phy_position_yprevious"
            | "phy_rotation"
            | "phy_sleeping"
            | "phy_speed"
            | "phy_speed_x"
            | "phy_speed_y"
            | "solid"
            | "speed"
            | "sprite_height"
            | "sprite_index"
            | "sprite_width"
            | "sprite_xoffset"
            | "sprite_yoffset"
            | "timeline_index"
            | "timeline_loop"
            | "timeline_position"
            | "timeline_running"
            | "timeline_speed"
            | "visible"
            | "vspeed"
            | "x"
            | "xprevious"
            | "xstart"
            | "y"
            | "yprevious"
            | "ystart"
    )
}
