//! Constants registered for classic projects by the GMS 1.4.9999 compiler but
//! absent from the Windows runner's own registration table. The compiler folds
//! these names into numeric VM operands, so a runner-derived list misses them.
//! Zeus- and pre-obfuscation-only constants are deliberately excluded.

pub(crate) const VALUES: &[(&str, f64)] = &[
    ("MATCHMAKING_CONNECTION", 3001.0),
    ("MATCHMAKING_INVITATION", 4001.0),
    ("MATCHMAKING_OPERATOR_EQUAL", 1.0),
    ("MATCHMAKING_OPERATOR_GREATERTHAN", 5.0),
    ("MATCHMAKING_OPERATOR_GREATERTHANOREQUAL", 6.0),
    ("MATCHMAKING_OPERATOR_LESSTHAN", 3.0),
    ("MATCHMAKING_OPERATOR_LESSTHANOREQUAL", 4.0),
    ("MATCHMAKING_OPERATOR_NOTEQUAL", 2.0),
    ("MATCHMAKING_PLAY_TOGETHER", 4002.0),
    ("MATCHMAKING_SESSION", 3002.0),
    ("PSN_LEADERBOARD_FRIENDS_SCORES_MSG", 2003.0),
    ("PSN_LEADERBOARD_SCORE_MSG", 2001.0),
    ("PSN_LEADERBOARD_SCORE_POSTED_MSG", 2004.0),
    ("PSN_LEADERBOARD_SCORE_RANGE_MSG", 2002.0),
    ("PSN_SERVICE_STATE", 5001.0),
    ("PSN_TROPHY_INFO_MSG", 102.0),
    ("PSN_TROPHY_UNLOCKED_MSG", 101.0),
    ("PSN_TROPHY_UNLOCK_STATE", 103.0),
    ("achievement_achievement_info", 1005.0),
    ("achievement_challenge_completed", 1007.0),
    ("achievement_challenge_completed_by_remote", 1008.0),
    ("achievement_challenge_launched", 1011.0),
    ("achievement_challenge_list_received", 1010.0),
    ("achievement_challenge_received", 1009.0),
    ("achievement_filter_all_players", 0.0),
    ("achievement_filter_favorites_alt", 4.0),
    ("achievement_filter_favorites_only", 2.0),
    ("achievement_filter_friends_alt", 3.0),
    ("achievement_filter_friends_only", 1.0),
    ("achievement_friends_info", 1003.0),
    ("achievement_leaderboard_info", 1004.0),
    ("achievement_msg_result", 1014.0),
    ("achievement_our_info", 1002.0),
    ("achievement_pic_loaded", 1006.0),
    ("achievement_player_info", 1012.0),
    ("achievement_purchase_info", 1013.0),
    ("achievement_show_achievement", 3.0),
    ("achievement_show_bank", 4.0),
    ("achievement_show_friend_picker", 5.0),
    ("achievement_show_leaderboard", 2.0),
    ("achievement_show_profile", 1.0),
    ("achievement_show_purchase_prompt", 6.0),
    ("achievement_show_ui", 0.0),
    ("achievement_stat_event", 1015.0),
    ("achievement_type_achievement_challenge", 0.0),
    ("achievement_type_score_challenge", 1.0),
    ("asset_background", 4.0),
    ("asset_font", 7.0),
    ("asset_object", 0.0),
    ("asset_path", 5.0),
    ("asset_room", 3.0),
    ("asset_script", 6.0),
    ("asset_shader", 10.0),
    ("asset_sound", 2.0),
    ("asset_sprite", 1.0),
    ("asset_timeline", 8.0),
    ("asset_unknown", -1.0),
    ("bm_complex", -1.0),
    ("browser_android_default", 7.0),
    ("browser_chrome", 3.0),
    ("browser_edge", 11.0),
    ("browser_firefox", 2.0),
    ("browser_ie", 1.0),
    ("browser_ie_mobile", 10.0),
    ("browser_not_a_browser", -1.0),
    ("browser_opera", 6.0),
    ("browser_safari", 4.0),
    ("browser_safari_mobile", 5.0),
    ("browser_tizen", 9.0),
    ("browser_unknown", 0.0),
    ("browser_windows_store", 8.0),
    ("cmpfunc_always", 8.0),
    ("cmpfunc_equal", 3.0),
    ("cmpfunc_greater", 5.0),
    ("cmpfunc_greaterequal", 7.0),
    ("cmpfunc_less", 2.0),
    ("cmpfunc_lessequal", 4.0),
    ("cmpfunc_never", 1.0),
    ("cmpfunc_notequal", 6.0),
    ("cull_clockwise", 1.0),
    ("cull_counterclockwise", 2.0),
    ("cull_noculling", 0.0),
    ("device_emulator", 256.0),
    ("device_ios_ipad", 2.0),
    ("device_ios_ipad_retina", 3.0),
    ("device_ios_iphone", 0.0),
    ("device_ios_iphone5", 4.0),
    ("device_ios_iphone6", 5.0),
    ("device_ios_iphone6plus", 6.0),
    ("device_ios_iphone6s", 7.0),
    ("device_ios_iphone6splus", 8.0),
    ("device_ios_iphone_retina", 1.0),
    ("device_ios_unknown", -1.0),
    ("device_tablet", 2.0),
    ("ds_type_grid", 5.0),
    ("ds_type_list", 2.0),
    ("ds_type_map", 1.0),
    ("ds_type_priority", 6.0),
    ("ds_type_queue", 4.0),
    ("ds_type_stack", 3.0),
    ("ev_draw_begin", 72.0),
    ("ev_draw_end", 73.0),
    ("ev_draw_post", 77.0),
    ("ev_draw_pre", 76.0),
    ("ev_gui_begin", 74.0),
    ("ev_gui_end", 75.0),
    ("fb_login_default", 0.0),
    ("fb_login_fallback_to_webview", 1.0),
    ("fb_login_forcing_safari", 5.0),
    ("fb_login_forcing_webview", 3.0),
    ("fb_login_no_fallback_to_webview", 2.0),
    ("fb_login_use_system_account", 4.0),
    ("gamespeed_fps", 0.0),
    ("gamespeed_microseconds", 1.0),
    ("iap_available", -1.0),
    ("iap_canceled", 1.0),
    ("iap_ev_consume", 3.0),
    ("iap_ev_product", 1.0),
    ("iap_ev_purchase", 2.0),
    ("iap_ev_restore", 4.0),
    ("iap_ev_storeload", 0.0),
    ("iap_failed", -3.0),
    ("iap_purchased", 0.0),
    ("iap_refunded", 2.0),
    ("iap_status_available", 1.0),
    ("iap_status_loading", 0.0),
    ("iap_status_processing", 2.0),
    ("iap_status_restoring", 3.0),
    ("iap_status_unavailable", -1.0),
    ("iap_status_uninitialised", -2.0),
    ("iap_storeload_failed", -1.0),
    ("iap_storeload_ok", 0.0),
    ("iap_unavailable", -2.0),
    ("leaderboard_type_number", 0.0),
    ("leaderboard_type_time_mins_secs", 1.0),
    ("lighttype_dir", 0.0),
    ("lighttype_point", 1.0),
    ("network_avoid_time_wait", 4.0),
    ("network_config_connect_timeout", 0.0),
    ("network_config_disable_reliable_udp", 3.0),
    ("network_config_enable_reliable_udp", 2.0),
    ("network_config_use_non_blocking_socket", 1.0),
    ("network_socket_bluetooth", 2.0),
    ("network_socket_tcp", 0.0),
    ("network_socket_tcp_psn", 3.0),
    ("network_socket_udp", 1.0),
    ("network_socket_udp_psn", 4.0),
    ("network_type_connect", 1.0),
    ("network_type_data", 3.0),
    ("network_type_disconnect", 2.0),
    ("network_type_non_blocking_connect", 4.0),
    ("of_challenge_lose", 1.0),
    ("of_challenge_tie", 2.0),
    ("of_challenge_win", 0.0),
    ("os_browser", -1.0),
    ("os_llvm_android", 65540.0),
    ("os_llvm_ios", 65539.0),
    ("os_llvm_linux", 65542.0),
    ("os_llvm_macosx", 65537.0),
    ("os_llvm_psp", 65538.0),
    ("os_llvm_symbian", 65541.0),
    ("os_llvm_win32", 65536.0),
    ("os_llvm_winphone", 65543.0),
    ("os_switch", 21.0),
    ("path_action_reverse", 3.0),
    ("phy_joint_angle_limits", 21.0),
    ("phy_joint_lower_angle_limit", 19.0),
    ("phy_joint_max_force", 24.0),
    ("phy_joint_max_length", 22.0),
    ("phy_joint_max_torque", 23.0),
    ("phy_joint_upper_angle_limit", 20.0),
    ("phy_particle_data_flag_category", 16.0),
    ("phy_particle_data_flag_colour", 8.0),
    ("phy_particle_data_flag_position", 2.0),
    ("phy_particle_data_flag_typeflags", 1.0),
    ("phy_particle_data_flag_velocity", 4.0),
    ("phy_particle_flag_colourmixing", 256.0),
    ("phy_particle_flag_elastic", 16.0),
    ("phy_particle_flag_powder", 64.0),
    ("phy_particle_flag_spring", 8.0),
    ("phy_particle_flag_tensile", 128.0),
    ("phy_particle_flag_viscous", 32.0),
    ("phy_particle_flag_wall", 4.0),
    ("phy_particle_flag_water", 0.0),
    ("phy_particle_flag_zombie", 2.0),
    ("phy_particle_group_flag_rigid", 2.0),
    ("phy_particle_group_flag_solid", 1.0),
    ("switch_controller_axis_x", 0.0),
    ("switch_controller_axis_y", 1.0),
    ("switch_controller_axis_z", 2.0),
    ("switch_controller_handheld", 1.0),
    ("switch_controller_handheld_activation_dual", 0.0),
    ("switch_controller_handheld_activation_none", 2.0),
    ("switch_controller_handheld_activation_single", 1.0),
    ("switch_controller_joycon_dual", 4.0),
    ("switch_controller_joycon_holdtype_horizontal", 1.0),
    ("switch_controller_joycon_holdtype_vertical", 0.0),
    ("switch_controller_joycon_left", 8.0),
    ("switch_controller_joycon_right", 16.0),
    ("switch_controller_motor_left", 0.0),
    ("switch_controller_motor_right", 1.0),
    ("switch_controller_motor_single", 0.0),
    ("switch_controller_pro_controller", 2.0),
    ("switch_irsensor_ambient_noise_high", 2.0),
    ("switch_irsensor_ambient_noise_low", 0.0),
    ("switch_irsensor_ambient_noise_middle", 1.0),
    ("switch_irsensor_ambient_noise_unknown", 3.0),
    ("switch_irsensor_hand_chirality_left", 1.0),
    ("switch_irsensor_hand_chirality_right", 2.0),
    ("switch_irsensor_hand_chirality_unknown", 3.0),
    ("switch_irsensor_hand_finger_count", 5.0),
    ("switch_irsensor_hand_finger_index", 1.0),
    ("switch_irsensor_hand_finger_little", 4.0),
    ("switch_irsensor_hand_finger_middle", 2.0),
    ("switch_irsensor_hand_finger_ring", 3.0),
    ("switch_irsensor_hand_finger_thumb", 0.0),
    ("switch_irsensor_hand_mode_image", 2.0),
    ("switch_irsensor_hand_mode_none", 0.0),
    ("switch_irsensor_hand_mode_silhouette", 1.0),
    ("switch_irsensor_hand_mode_silhouette_and_image", 3.0),
    ("switch_irsensor_hand_mode_silhouette_only", 4.0),
    ("switch_irsensor_hand_touching_count", 3.0),
    ("switch_irsensor_hand_touching_index_middle", 0.0),
    ("switch_irsensor_hand_touching_middle_ring", 1.0),
    ("switch_irsensor_hand_touching_ring_little", 2.0),
    ("switch_irsensor_image_format_160x120", 1.0),
    ("switch_irsensor_image_format_20x15", 4.0),
    ("switch_irsensor_image_format_320x240", 0.0),
    ("switch_irsensor_image_format_40x30", 3.0),
    ("switch_irsensor_image_format_80x60", 2.0),
    ("switch_irsensor_image_format_qqqvga", 2.0),
    ("switch_irsensor_image_format_qqvga", 1.0),
    ("switch_irsensor_image_format_qvga", 0.0),
    ("switch_irsensor_light_target_all", 0.0),
    ("switch_irsensor_light_target_far", 1.0),
    ("switch_irsensor_light_target_near", 2.0),
    ("switch_irsensor_light_target_none", 3.0),
    ("switch_irsensor_mode_cluster", 2.0),
    ("switch_irsensor_mode_hand", 4.0),
    ("switch_irsensor_mode_image", 3.0),
    ("switch_irsensor_mode_moment", 1.0),
    ("switch_irsensor_mode_none", 0.0),
    ("switch_irsensor_moment_preprocess_binarize", 0.0),
    ("switch_irsensor_moment_preprocess_cutoff", 1.0),
    (
        "switch_performance_config_Cpu1020MhzGpu307MhzEmc1331Mhz",
        131075.0,
    ),
    (
        "switch_performance_config_Cpu1020MhzGpu384MhzEmc1331Mhz",
        131076.0,
    ),
    (
        "switch_performance_config_Cpu1020MhzGpu768MhzEmc1600Mhz",
        65537.0,
    ),
    ("switch_performance_config_invalid", 0.0),
    ("switch_performance_mode_boost", 1.0),
    ("switch_performance_mode_invalid", -1.0),
    ("switch_performance_mode_normal", 0.0),
    ("switch_screenshot_rotation_180", 2.0),
    ("switch_screenshot_rotation_270", 3.0),
    ("switch_screenshot_rotation_90", 1.0),
    ("switch_screenshot_rotation_none", 0.0),
    ("switch_theme_black", 3.0),
    ("switch_theme_default", 0.0),
    ("switch_theme_user", 1.0),
    ("switch_theme_white", 2.0),
    ("tm_countvsyncs", 1.0),
    ("tm_sleep", 0.0),
    ("uwp_privilege_communications", 252.0),
    ("uwp_privilege_fitness_upload", 195.0),
    ("uwp_privilege_internet_browsing", 217.0),
    ("uwp_privilege_multiplayer_sessions", 254.0),
    ("uwp_privilege_result_aborted", 2.0),
    ("uwp_privilege_result_banned", 4.0),
    ("uwp_privilege_result_no_issue", 0.0),
    ("uwp_privilege_result_purchase_required", 1.0),
    ("uwp_privilege_result_restricted", 8.0),
    ("uwp_privilege_sessions", 189.0),
    ("uwp_privilege_share_kinect_content", 199.0),
    ("uwp_privilege_social_network_sharing", 220.0),
    ("uwp_privilege_user_created_content", 247.0),
    ("uwp_privilege_video_communications", 235.0),
    ("vbm_compatible", 1.0),
    ("vbm_fast", 0.0),
    ("vbm_most_compatible", 2.0),
    ("vertex_type_colour", 5.0),
    ("vertex_type_float1", 1.0),
    ("vertex_type_float2", 2.0),
    ("vertex_type_float3", 3.0),
    ("vertex_type_float4", 4.0),
    ("vertex_type_ubyte4", 6.0),
    ("vertex_usage_binormal", 9.0),
    ("vertex_usage_blendindices", 6.0),
    ("vertex_usage_blendweight", 5.0),
    ("vertex_usage_colour", 2.0),
    ("vertex_usage_depth", 13.0),
    ("vertex_usage_fog", 12.0),
    ("vertex_usage_normal", 3.0),
    ("vertex_usage_position", 1.0),
    ("vertex_usage_psize", 7.0),
    ("vertex_usage_sample", 14.0),
    ("vertex_usage_tangent", 8.0),
    ("vertex_usage_texcoord", 4.0),
    ("vertex_usage_textcoord", 4.0),
    ("xboxlive_agegroup_adult", 3.0),
    ("xboxlive_agegroup_child", 1.0),
    ("xboxlive_agegroup_teen", 2.0),
    ("xboxlive_agegroup_unknown", 0.0),
    ("xboxlive_fileerror_blobnotfound", 5.0),
    ("xboxlive_fileerror_cantopenfile", 4.0),
    ("xboxlive_fileerror_containernotinsync", 6.0),
    ("xboxlive_fileerror_containersyncfailed", 7.0),
    ("xboxlive_fileerror_invalidcontainername", 8.0),
    ("xboxlive_fileerror_noaccess", 9.0),
    ("xboxlive_fileerror_noerror", 0.0),
    ("xboxlive_fileerror_noxboxliveinfo", 10.0),
    ("xboxlive_fileerror_outoflocalstorage", 11.0),
    ("xboxlive_fileerror_outofmemory", 1.0),
    ("xboxlive_fileerror_providedbuffertoosmall", 12.0),
    ("xboxlive_fileerror_quotaexceeded", 13.0),
    ("xboxlive_fileerror_unknownerror", 3.0),
    ("xboxlive_fileerror_updatetoobig", 14.0),
    ("xboxlive_fileerror_usercanceled", 15.0),
    ("xboxlive_fileerror_usernotfound", 2.0),
    ("xboxlive_gamerpic_large", 3.0),
    ("xboxlive_gamerpic_medium", 2.0),
    ("xboxlive_gamerpic_small", 1.0),
    ("xboxlive_match_visibility_open", 1.0),
    ("xboxlive_match_visibility_private", 2.0),
    ("xboxlive_match_visibility_usetemplate", 0.0),
    ("xboxone_agegroup_adult", 3.0),
    ("xboxone_agegroup_child", 1.0),
    ("xboxone_agegroup_teen", 2.0),
    ("xboxone_agegroup_unknown", 0.0),
    ("xboxone_fileerror_blobnotfound", 5.0),
    ("xboxone_fileerror_cantopenfile", 4.0),
    ("xboxone_fileerror_containernotinsync", 6.0),
    ("xboxone_fileerror_containersyncfailed", 7.0),
    ("xboxone_fileerror_invalidcontainername", 8.0),
    ("xboxone_fileerror_noaccess", 9.0),
    ("xboxone_fileerror_noerror", 0.0),
    ("xboxone_fileerror_noxboxliveinfo", 10.0),
    ("xboxone_fileerror_outoflocalstorage", 11.0),
    ("xboxone_fileerror_outofmemory", 1.0),
    ("xboxone_fileerror_providedbuffertoosmall", 12.0),
    ("xboxone_fileerror_quotaexceeded", 13.0),
    ("xboxone_fileerror_unknownerror", 3.0),
    ("xboxone_fileerror_updatetoobig", 14.0),
    ("xboxone_fileerror_usercanceled", 15.0),
    ("xboxone_fileerror_usernotfound", 2.0),
    ("xboxone_gamerpic_large", 3.0),
    ("xboxone_gamerpic_medium", 2.0),
    ("xboxone_gamerpic_small", 1.0),
    ("xboxone_match_visibility_open", 1.0),
    ("xboxone_match_visibility_private", 2.0),
    ("xboxone_match_visibility_usetemplate", 0.0),
    ("xboxone_privilege_communications", 252.0),
    ("xboxone_privilege_fitness_upload", 195.0),
    ("xboxone_privilege_internet_browsing", 217.0),
    ("xboxone_privilege_multiplayer_sessions", 254.0),
    ("xboxone_privilege_result_aborted", 2.0),
    ("xboxone_privilege_result_banned", 4.0),
    ("xboxone_privilege_result_no_issue", 0.0),
    ("xboxone_privilege_result_purchase_required", 1.0),
    ("xboxone_privilege_result_restricted", 8.0),
    ("xboxone_privilege_sessions", 189.0),
    ("xboxone_privilege_share_kinect_content", 199.0),
    ("xboxone_privilege_social_network_sharing", 220.0),
    ("xboxone_privilege_user_created_content", 247.0),
    ("xboxone_privilege_video_communications", 235.0),
];

pub(crate) fn names() -> impl Iterator<Item = &'static str> {
    VALUES.iter().map(|(name, _)| *name)
}

pub(crate) fn value(name: &str) -> Option<f64> {
    let index = VALUES
        .binary_search_by(|(candidate, _)| candidate.cmp(&name))
        .ok()?;
    Some(VALUES[index].1)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn table_is_sorted_and_has_unique_names() {
        assert!(VALUES.windows(2).all(|pair| pair[0].0 < pair[1].0));
    }

    #[test]
    fn contains_legacy_graphics_constant_families() {
        assert_eq!(value("vbm_fast"), Some(0.0));
        assert_eq!(value("vbm_compatible"), Some(1.0));
        assert_eq!(value("vbm_most_compatible"), Some(2.0));
        assert_eq!(value("vertex_usage_position"), Some(1.0));
        assert_eq!(value("vertex_type_float4"), Some(4.0));
        assert_eq!(value("cmpfunc_always"), Some(8.0));
        assert_eq!(value("cull_counterclockwise"), Some(2.0));
        assert_eq!(value("lighttype_point"), Some(1.0));
    }
}
